<?php
// IMPORTANT: Build city context and meta BEFORE including header (no output above)
// Get city name from URL and sanitize it
$citySlug = isset($_GET['city']) ? strtolower(trim($_GET_GET['city'])) : '';
$cityName = ucwords(str_replace('-', ' ', $citySlug));
// List of supported cities (Tamil Nadu) - Existing list from Pasted_Text_1756571897409.txt
$supportedCities = [
    // Major cities
    'chennai' => ['name' => 'Chennai', 'state' => 'Tamil Nadu'],
    'madurai' => ['name' => 'Madurai', 'state' => 'Tamil Nadu'],
    'coimbatore' => ['name' => 'Coimbatore', 'state' => 'Tamil Nadu'],
    'tiruchirappalli' => ['name' => 'Tiruchirappalli', 'state' => 'Tamil Nadu'],
    'thoothukudi' => ['name' => 'Thoothukudi', 'state' => 'Tamil Nadu'],
    'dindigul' => ['name' => 'Dindigul', 'state' => 'Tamil Nadu'],
    'thanjavur' => ['name' => 'Thanjavur', 'state' => 'Tamil Nadu'],
    'nagercoil' => ['name' => 'Nagercoil', 'state' => 'Tamil Nadu'],
    'hosur' => ['name' => 'Hosur', 'state' => 'Tamil Nadu'],
    'avadi' => ['name' => 'Avadi', 'state' => 'Tamil Nadu'],
    'kumbakonam' => ['name' => 'Kumbakonam', 'state' => 'Tamil Nadu'],
    'cuddalore' => ['name' => 'Cuddalore', 'state' => 'Tamil Nadu'],
    'karur' => ['name' => 'Karur', 'state' => 'Tamil Nadu'],
    'sivakasi' => ['name' => 'Sivakasi', 'state' => 'Tamil Nadu'],
    'tambaram' => ['name' => 'Tambaram', 'state' => 'Tamil Nadu'],
    'karaikudi' => ['name' => 'Karaikudi', 'state' => 'Tamil Nadu'],
    'namakkal' => ['name' => 'Namakkal', 'state' => 'Tamil Nadu'],
    'chengalpattu' => ['name' => 'Chengalpattu', 'state' => 'Tamil Nadu'],
    'kanchipuram' => ['name' => 'Kanchipuram', 'state' => 'Tamil Nadu'],
    'ooty' => ['name' => 'Ooty', 'state' => 'Tamil Nadu'],
    'nagapattinam' => ['name' => 'Nagapattinam', 'state' => 'Tamil Nadu'],
    'ariyalur' => ['name' => 'Ariyalur', 'state' => 'Tamil Nadu'],
    'virudhunagar' => ['name' => 'Virudhunagar', 'state' => 'Tamil Nadu'],
    'tenkasi' => ['name' => 'Tenkasi', 'state' => 'Tamil Nadu'],
    'ramanathapuram' => ['name' => 'Ramanathapuram', 'state' => 'Tamil Nadu'],
    'theni' => ['name' => 'Theni', 'state' => 'Tamil Nadu'],
    'sivagangai' => ['name' => 'Sivagangai', 'state' => 'Tamil Nadu'],
    'dharmapuri' => ['name' => 'Dharmapuri', 'state' => 'Tamil Nadu'],
    'krishnagiri' => ['name' => 'Krishnagiri', 'state' => 'Tamil Nadu'],
    'nilgiris' => ['name' => 'Nilgiris', 'state' => 'Tamil Nadu'],
    'thiruvarur' => ['name' => 'Thiruvarur', 'state' => 'Tamil Nadu'],
    'mayiladuthurai' => ['name' => 'Mayiladuthurai', 'state' => 'Tamil Nadu'],
    // Additional cities and towns
    'tiruttani' => ['name' => 'Tiruttani', 'state' => 'Tamil Nadu'],
    'ponneri' => ['name' => 'Ponneri', 'state' => 'Tamil Nadu'],
    'naravarikuppam' => ['name' => 'Naravarikuppam', 'state' => 'Tamil Nadu'],
    'veppampattu' => ['name' => 'Veppampattu', 'state' => 'Tamil Nadu'],
    'maduranthakam' => ['name' => 'Maduranthakam', 'state' => 'Tamil Nadu'],
    'mamallapuram' => ['name' => 'Mamallapuram', 'state' => 'Tamil Nadu'],
    'maraimalai-nagar' => ['name' => 'Maraimalai Nagar', 'state' => 'Tamil Nadu'],
    'nandivaram' => ['name' => 'Nandivaram', 'state' => 'Tamil Nadu'],
    'tirukalukundram' => ['name' => 'Tirukalukundram', 'state' => 'Tamil Nadu'],
    'kundrathur' => ['name' => 'Kundrathur', 'state' => 'Tamil Nadu'],
    'mangadu' => ['name' => 'Mangadu', 'state' => 'Tamil Nadu'],
    'sriperumbudur' => ['name' => 'Sriperumbudur', 'state' => 'Tamil Nadu'],
    'chidambaram' => ['name' => 'Chidambaram', 'state' => 'Tamil Nadu'],
    'panruti' => ['name' => 'Panruti', 'state' => 'Tamil Nadu'],
    'nellikuppam' => ['name' => 'Nellikuppam', 'state' => 'Tamil Nadu'],
    'tittakudi' => ['name' => 'Tittakudi', 'state' => 'Tamil Nadu'],
    'vadalur' => ['name' => 'Vadalur', 'state' => 'Tamil Nadu'],
    'virudhachalam' => ['name' => 'Virudhachalam', 'state' => 'Tamil Nadu'],
    'viluppuram' => ['name' => 'Viluppuram', 'state' => 'Tamil Nadu'],
    'kallakurichi' => ['name' => 'Kallakurichi', 'state' => 'Tamil Nadu'],
    'ranipet' => ['name' => 'Ranipet', 'state' => 'Tamil Nadu'],
    'tirupathur' => ['name' => 'Tirupathur', 'state' => 'Tamil Nadu'],
    'kottakuppam' => ['name' => 'Kottakuppam', 'state' => 'Tamil Nadu'],
    'tindivanam' => ['name' => 'Tindivanam', 'state' => 'Tamil Nadu'],
    'arni' => ['name' => 'Arni', 'state' => 'Tamil Nadu'],
    'tirukoilur' => ['name' => 'Tirukoilur', 'state' => 'Tamil Nadu'],
    'ulundurpettai' => ['name' => 'Ulundurpettai', 'state' => 'Tamil Nadu'],
    'gudiyatham' => ['name' => 'Gudiyatham', 'state' => 'Tamil Nadu'],
    'pernambut' => ['name' => 'Pernambut', 'state' => 'Tamil Nadu'],
    'arakkonam' => ['name' => 'Arakkonam', 'state' => 'Tamil Nadu'],
    'arcot' => ['name' => 'Arcot', 'state' => 'Tamil Nadu'],
    'melvisharam' => ['name' => 'Melvisharam', 'state' => 'Tamil Nadu'],
    'sholinghur' => ['name' => 'Sholinghur', 'state' => 'Tamil Nadu'],
    'walajapet' => ['name' => 'Walajapet', 'state' => 'Tamil Nadu'],
    'ambur' => ['name' => 'Ambur', 'state' => 'Tamil Nadu'],
    'jolarpettai' => ['name' => 'Jolarpettai', 'state' => 'Tamil Nadu'],
    'tirupattur' => ['name' => 'Tirupattur', 'state' => 'Tamil Nadu'],
    'vaniyambadi' => ['name' => 'Vaniyambadi', 'state' => 'Tamil Nadu'],
    'chengam' => ['name' => 'Chengam', 'state' => 'Tamil Nadu'],
    'polur' => ['name' => 'Polur', 'state' => 'Tamil Nadu'],
    'harur' => ['name' => 'Harur', 'state' => 'Tamil Nadu'],
    'attur' => ['name' => 'Attur', 'state' => 'Tamil Nadu'],
    'edaganasalai' => ['name' => 'Edaganasalai', 'state' => 'Tamil Nadu'],
    'edappadi' => ['name' => 'Edappadi', 'state' => 'Tamil Nadu'],
    'mettur' => ['name' => 'Mettur', 'state' => 'Tamil Nadu'],
    'narasingapuram' => ['name' => 'Narasingapuram', 'state' => 'Tamil Nadu'],
    'sangagiri' => ['name' => 'Sangagiri', 'state' => 'Tamil Nadu'],
    'tharamangalam' => ['name' => 'Tharamangalam', 'state' => 'Tamil Nadu'],
    'komarapalayam' => ['name' => 'Komarapalayam', 'state' => 'Tamil Nadu'],
    'mohanur' => ['name' => 'Mohanur', 'state' => 'Tamil Nadu'],
    'pallipalayam' => ['name' => 'Pallipalayam', 'state' => 'Tamil Nadu'],
    'rasipuram' => ['name' => 'Rasipuram', 'state' => 'Tamil Nadu'],
    'tiruchengode' => ['name' => 'Tiruchengode', 'state' => 'Tamil Nadu'],
    'velur' => ['name' => 'Velur', 'state' => 'Tamil Nadu'],
    'kulithalai' => ['name' => 'Kulithalai', 'state' => 'Tamil Nadu'],
    'pallapatti' => ['name' => 'Pallapatti', 'state' => 'Tamil Nadu'],
    'pugalur' => ['name' => 'Pugalur', 'state' => 'Tamil Nadu'],
    'mettupalayam' => ['name' => 'Mettupalayam', 'state' => 'Tamil Nadu'],
    'karamadai' => ['name' => 'Karamadai', 'state' => 'Tamil Nadu'],
    'udagamandalam' => ['name' => 'Udagamandalam', 'state' => 'Tamil Nadu'],
    'gudalur' => ['name' => 'Gudalur', 'state' => 'Tamil Nadu'],
    'karumathampatti' => ['name' => 'Karumathampatti', 'state' => 'Tamil Nadu'],
    'sulur' => ['name' => 'Sulur', 'state' => 'Tamil Nadu'],
    'pollachi' => ['name' => 'Pollachi', 'state' => 'Tamil Nadu'],
    'valparai' => ['name' => 'Valparai', 'state' => 'Tamil Nadu'],
    'bhavani' => ['name' => 'Bhavani', 'state' => 'Tamil Nadu'],
    'gobichettipalayam' => ['name' => 'Gobichettipalayam', 'state' => 'Tamil Nadu'],
    'kavandapadi' => ['name' => 'Kavandapadi', 'state' => 'Tamil Nadu'],
    'perundurai' => ['name' => 'Perundurai', 'state' => 'Tamil Nadu'],
    'punjai-puliampatti' => ['name' => 'Punjai Puliampatti', 'state' => 'Tamil Nadu'],
    'sathyamangalam' => ['name' => 'Sathyamangalam', 'state' => 'Tamil Nadu'],
    'avinashi' => ['name' => 'Avinashi', 'state' => 'Tamil Nadu'],
    'dharapuram' => ['name' => 'Dharapuram', 'state' => 'Tamil Nadu'],
    'kangeyam' => ['name' => 'Kangeyam', 'state' => 'Tamil Nadu'],
    'palladam' => ['name' => 'Palladam', 'state' => 'Tamil Nadu'],
    'thirumuruganpoondi' => ['name' => 'Thirumuruganpoondi', 'state' => 'Tamil Nadu'],
    'udumalaipettai' => ['name' => 'Udumalaipettai', 'state' => 'Tamil Nadu'],
    'vellakoil' => ['name' => 'Vellakoil', 'state' => 'Tamil Nadu'],
    'manachanallur' => ['name' => 'Manachanallur', 'state' => 'Tamil Nadu'],
    'manapparai' => ['name' => 'Manapparai', 'state' => 'Tamil Nadu'],
    'musiri' => ['name' => 'Musiri', 'state' => 'Tamil Nadu'],
    'lalgudi' => ['name' => 'Lalgudi', 'state' => 'Tamil Nadu'],
    'thuraiyur' => ['name' => 'Thuraiyur', 'state' => 'Tamil Nadu'],
    'thuvakudi' => ['name' => 'Thuvakudi', 'state' => 'Tamil Nadu'],
    'vedaranyam' => ['name' => 'Vedaranyam', 'state' => 'Tamil Nadu'],
    'sirkazhi' => ['name' => 'Sirkazhi', 'state' => 'Tamil Nadu'],
    'jayankondam' => ['name' => 'Jayankondam', 'state' => 'Tamil Nadu'],
    'perambalur' => ['name' => 'Perambalur', 'state' => 'Tamil Nadu'],
    'koothanallur' => ['name' => 'Koothanallur', 'state' => 'Tamil Nadu'],
    'mannargudi' => ['name' => 'Mannargudi', 'state' => 'Tamil Nadu'],
    'thiruthuraipoondi' => ['name' => 'Thiruthuraipoondi', 'state' => 'Tamil Nadu'],
    'adirampattinam' => ['name' => 'Adirampattinam', 'state' => 'Tamil Nadu'],
    'pattukkottai' => ['name' => 'Pattukkottai', 'state' => 'Tamil Nadu'],
    'thiruvaiyaru' => ['name' => 'Thiruvaiyaru', 'state' => 'Tamil Nadu'],
    'aranthangi' => ['name' => 'Aranthangi', 'state' => 'Tamil Nadu'],
    'melur' => ['name' => 'Melur', 'state' => 'Tamil Nadu'],
    'thirumangalam' => ['name' => 'Thirumangalam', 'state' => 'Tamil Nadu'],
    'usilampatti' => ['name' => 'Usilampatti', 'state' => 'Tamil Nadu'],
    'bodinayakkanur' => ['name' => 'Bodinayakkanur', 'state' => 'Tamil Nadu'],
    'chinnamanur' => ['name' => 'Chinnamanur', 'state' => 'Tamil Nadu'],
    'cumbum' => ['name' => 'Cumbum', 'state' => 'Tamil Nadu'],
    'periyakulam' => ['name' => 'Periyakulam', 'state' => 'Tamil Nadu'],
    'theni-allinagaram' => ['name' => 'Theni Allinagaram', 'state' => 'Tamil Nadu'],
    'uthamapalayam' => ['name' => 'Uthamapalayam', 'state' => 'Tamil Nadu'],
    'kodaikanal' => ['name' => 'Kodaikanal', 'state' => 'Tamil Nadu'],
    'oddanchatram' => ['name' => 'Oddanchatram', 'state' => 'Tamil Nadu'],
    'palani' => ['name' => 'Palani', 'state' => 'Tamil Nadu'],
    'devakottai' => ['name' => 'Devakottai', 'state' => 'Tamil Nadu'],
    'manamadurai' => ['name' => 'Manamadurai', 'state' => 'Tamil Nadu'],
    'kilakarai' => ['name' => 'Kilakarai', 'state' => 'Tamil Nadu'],
    'paramakudi' => ['name' => 'Paramakudi', 'state' => 'Tamil Nadu'],
    'rameswaram' => ['name' => 'Rameswaram', 'state' => 'Tamil Nadu'],
    'guduvancheri' => ['name' => 'Guduvancheri', 'state' => 'Tamil Nadu'],
    'ambasamudram' => ['name' => 'Ambasamudram', 'state' => 'Tamil Nadu'],
    'kalakkad' => ['name' => 'Kalakkad', 'state' => 'Tamil Nadu'],
    'kuzhithurai' => ['name' => 'Kuzhithurai', 'state' => 'Tamil Nadu'],
    'vadakkuvalliyur' => ['name' => 'Vadakkuvalliyur', 'state' => 'Tamil Nadu'],
    'vikramasingapuram' => ['name' => 'Vikramasingapuram', 'state' => 'Tamil Nadu'],
    'kadayanallur' => ['name' => 'Kadayanallur', 'state' => 'Tamil Nadu'],
    'puliyankudi' => ['name' => 'Puliyankudi', 'state' => 'Tamil Nadu'],
    'sankarankovil' => ['name' => 'Sankarankovil', 'state' => 'Tamil Nadu'],
    'sengottai' => ['name' => 'Sengottai', 'state' => 'Tamil Nadu'],
    'surandai' => ['name' => 'Surandai', 'state' => 'Tamil Nadu'],
    'aruppukkottai' => ['name' => 'Aruppukkottai', 'state' => 'Tamil Nadu'],
    'rajapalayam' => ['name' => 'Rajapalayam', 'state' => 'Tamil Nadu'],
    'sattur' => ['name' => 'Sattur', 'state' => 'Tamil Nadu'],
    'srivilliputhur' => ['name' => 'Srivilliputhur', 'state' => 'Tamil Nadu'],
    'kayalpatnam' => ['name' => 'Kayalpatnam', 'state' => 'Tamil Nadu'],
    'kovilpatti' => ['name' => 'Kovilpatti', 'state' => 'Tamil Nadu'],
    'tiruchendur' => ['name' => 'Tiruchendur', 'state' => 'Tamil Nadu'],
    'padmanabhapuram' => ['name' => 'Padmanabhapuram', 'state' => 'Tamil Nadu'],
    'colachel' => ['name' => 'Colachel', 'state' => 'Tamil Nadu'],
    'andimadam' => ['name' => 'Andimadam', 'state' => 'Tamil Nadu'],
    'sendurai' => ['name' => 'Sendurai', 'state' => 'Tamil Nadu'],
    'udayarpalayam' => ['name' => 'Udayarpalayam', 'state' => 'Tamil Nadu'],
    'thirukkalukundram' => ['name' => 'Thirukkalukundram', 'state' => 'Tamil Nadu'],
    'thirupporur' => ['name' => 'Thirupporur', 'state' => 'Tamil Nadu'],
    'chevyur' => ['name' => 'Chevyur', 'state' => 'Tamil Nadu'],
    'pallavaram' => ['name' => 'Pallavaram', 'state' => 'Tamil Nadu'],
    'vandalur' => ['name' => 'Vandalur', 'state' => 'Tamil Nadu'],
    'ambattur' => ['name' => 'Ambattur', 'state' => 'Tamil Nadu'],
    'aminjikarai' => ['name' => 'Aminjikarai', 'state' => 'Tamil Nadu'],
    'ayanavaram' => ['name' => 'Ayanavaram', 'state' => 'Tamil Nadu'],
    'egmore' => ['name' => 'Egmore', 'state' => 'Tamil Nadu'],
    'maduravoyal' => ['name' => 'Maduravoyal', 'state' => 'Tamil Nadu'],
    'mambalam' => ['name' => 'Mambalam', 'state' => 'Tamil Nadu'],
    'madhavaram' => ['name' => 'Madhavaram', 'state' => 'Tamil Nadu'],
    'perambur' => ['name' => 'Perambur', 'state' => 'Tamil Nadu'],
    'purasawalkam' => ['name' => 'Purasawalkam', 'state' => 'Tamil Nadu'],
    'thiruvottiyur' => ['name' => 'Thiruvottiyur', 'state' => 'Tamil Nadu'],
    'tondiarpet' => ['name' => 'Tondiarpet', 'state' => 'Tamil Nadu'],
    'alandur' => ['name' => 'Alandur', 'state' => 'Tamil Nadu'],
    'guindy' => ['name' => 'Guindy', 'state' => 'Tamil Nadu'],
    'mylapore' => ['name' => 'Mylapore', 'state' => 'Tamil Nadu'],
    'sholinganallur' => ['name' => 'Sholinganallur', 'state' => 'Tamil Nadu'],
    'velachery' => ['name' => 'Velachery', 'state' => 'Tamil Nadu'],
    'annur' => ['name' => 'Annur', 'state' => 'Tamil Nadu'],
    'coimbatore-north' => ['name' => 'Coimbatore North', 'state' => 'Tamil Nadu'],
    'coimbatore-south' => ['name' => 'Coimbatore South', 'state' => 'Tamil Nadu'],
    'madukkarai' => ['name' => 'Madukkarai', 'state' => 'Tamil Nadu'],
    'perur' => ['name' => 'Perur', 'state' => 'Tamil Nadu'],
    'anaimalai' => ['name' => 'Anaimalai', 'state' => 'Tamil Nadu'],
    'kinathukadavu' => ['name' => 'Kinathukadavu', 'state' => 'Tamil Nadu'],
    'bhuvanagiri' => ['name' => 'Bhuvanagiri', 'state' => 'Tamil Nadu'],
    'kattumannarkoil' => ['name' => 'Kattumannarkoil', 'state' => 'Tamil Nadu'],
    'srimushnam' => ['name' => 'Srimushnam', 'state' => 'Tamil Nadu'],
    'kurinjipadi' => ['name' => 'Kurinjipadi', 'state' => 'Tamil Nadu'],
    'veppur' => ['name' => 'Veppur', 'state' => 'Tamil Nadu'],
    'karimangalam' => ['name' => 'Karimangalam', 'state' => 'Tamil Nadu'],
    'nallampalli' => ['name' => 'Nallampalli', 'state' => 'Tamil Nadu'],
    'palacode' => ['name' => 'Palacode', 'state' => 'Tamil Nadu'],
    'pennagaram' => ['name' => 'Pennagaram', 'state' => 'Tamil Nadu'],
    'pappireddipatti' => ['name' => 'Pappireddipatti', 'state' => 'Tamil Nadu'],
    'athoor' => ['name' => 'Athoor', 'state' => 'Tamil Nadu'],
    'dindigul-east' => ['name' => 'Dindigul East', 'state' => 'Tamil Nadu'],
    'dindigul-west' => ['name' => 'Dindigul West', 'state' => 'Tamil Nadu'],
    'natham' => ['name' => 'Natham', 'state' => 'Tamil Nadu'],
    'nilakottai' => ['name' => 'Nilakottai', 'state' => 'Tamil Nadu'],
    'gujiliamparai' => ['name' => 'Gujiliamparai', 'state' => 'Tamil Nadu'],
    'vedasandur' => ['name' => 'Vedasandur', 'state' => 'Tamil Nadu'],
    'kodumudi' => ['name' => 'Kodumudi', 'state' => 'Tamil Nadu'],
    'modakkurichi' => ['name' => 'Modakkurichi', 'state' => 'Tamil Nadu'],
    'anthiyur' => ['name' => 'Anthiyur', 'state' => 'Tamil Nadu'],
    'nambiyur' => ['name' => 'Nambiyur', 'state' => 'Tamil Nadu'],
    'thalavadi' => ['name' => 'Thalavadi', 'state' => 'Tamil Nadu'],
    'chinnasalem' => ['name' => 'Chinnasalem', 'state' => 'Tamil Nadu'],
    'kalvarayan-hills' => ['name' => 'Kalvarayan Hills', 'state' => 'Tamil Nadu'],
    'sankarapuram' => ['name' => 'Sankarapuram', 'state' => 'Tamil Nadu'],
    'tirukovilur' => ['name' => 'Tirukovilur', 'state' => 'Tamil Nadu'],
    'ulundurpet' => ['name' => 'Ulundurpet', 'state' => 'Tamil Nadu'],
    'uthiramerur' => ['name' => 'Uthiramerur', 'state' => 'Tamil Nadu'],
    'walajabad' => ['name' => 'Walajabad', 'state' => 'Tamil Nadu'],
    'agastheeswaram' => ['name' => 'Agastheeswaram', 'state' => 'Tamil Nadu'],
    'thovalai' => ['name' => 'Thovalai', 'state' => 'Tamil Nadu'],
    'kalkulam' => ['name' => 'Kalkulam', 'state' => 'Tamil Nadu'],
    'killiyoor' => ['name' => 'Killiyoor', 'state' => 'Tamil Nadu'],
    'thiruvattar' => ['name' => 'Thiruvattar', 'state' => 'Tamil Nadu'],
    'vilavancode' => ['name' => 'Vilavancode', 'state' => 'Tamil Nadu'],
    'aravakurichi' => ['name' => 'Aravakurichi', 'state' => 'Tamil Nadu'],
    'krishnarayapuram' => ['name' => 'Krishnarayapuram', 'state' => 'Tamil Nadu'],
    'kadavur' => ['name' => 'Kadavur', 'state' => 'Tamil Nadu'],
    'anchetty' => ['name' => 'Anchetty', 'state' => 'Tamil Nadu'],
    'denkanikottai' => ['name' => 'Denkanikottai', 'state' => 'Tamil Nadu'],
    'shoolagiri' => ['name' => 'Shoolagiri', 'state' => 'Tamil Nadu'],
    'bargur' => ['name' => 'Bargur', 'state' => 'Tamil Nadu'],
    'pochampalli' => ['name' => 'Pochampalli', 'state' => 'Tamil Nadu'],
    'uthangarai' => ['name' => 'Uthangarai', 'state' => 'Tamil Nadu'],
    'madurai-north' => ['name' => 'Madurai North', 'state' => 'Tamil Nadu'],
    'madurai-west' => ['name' => 'Madurai West', 'state' => 'Tamil Nadu'],
    'madurai-east' => ['name' => 'Madurai East', 'state' => 'Tamil Nadu'],
    'madurai-south' => ['name' => 'Madurai South', 'state' => 'Tamil Nadu'],
    'kalligudi' => ['name' => 'Kalligudi', 'state' => 'Tamil Nadu'],
    'thirupparankundram' => ['name' => 'Thirupparankundram', 'state' => 'Tamil Nadu'],
    'peraiyur' => ['name' => 'Peraiyur', 'state' => 'Tamil Nadu'],
    'muthupettai' => ['name' => 'Muthupettai', 'state' => 'Tamil Nadu'],
    'needamangalam' => ['name' => 'Needamangalam', 'state' => 'Tamil Nadu'],
    'kudavasal' => ['name' => 'Kudavasal', 'state' => 'Tamil Nadu'],
    'nannilam' => ['name' => 'Nannilam', 'state' => 'Tamil Nadu'],
    'valangaiman' => ['name' => 'Valangaiman', 'state' => 'Tamil Nadu'],
    'papanasam' => ['name' => 'Papanasam', 'state' => 'Tamil Nadu'],
    'thiruvidaimarudur' => ['name' => 'Thiruvidaimarudur', 'state' => 'Tamil Nadu'],
    'peravurani' => ['name' => 'Peravurani', 'state' => 'Tamil Nadu'],
    'orathanadu' => ['name' => 'Orathanadu', 'state' => 'Tamil Nadu'],
    'budalur' => ['name' => 'Budalur', 'state' => 'Tamil Nadu'],
    'aundipatti' => ['name' => 'Aundipatti', 'state' => 'Tamil Nadu'],
    'thottiyam' => ['name' => 'Thottiyam', 'state' => 'Tamil Nadu'],
    'marungapuri' => ['name' => 'Marungapuri', 'state' => 'Tamil Nadu'],
    'srirangam' => ['name' => 'Srirangam', 'state' => 'Tamil Nadu'],
    'tiruchirappalli-west' => ['name' => 'Tiruchirappalli West', 'state' => 'Tamil Nadu'],
    'tiruverumbur' => ['name' => 'Tiruverumbur', 'state' => 'Tamil Nadu'],
    'tiruchirappalli-east' => ['name' => 'Tiruchirappalli East', 'state' => 'Tamil Nadu'],
    'natrampalli' => ['name' => 'Natrampalli', 'state' => 'Tamil Nadu'],
    'kuthalam' => ['name' => 'Kuthalam', 'state' => 'Tamil Nadu'],
    'tharangambadi' => ['name' => 'Tharangambadi', 'state' => 'Tamil Nadu'],
    'kilvelur' => ['name' => 'Kilvelur', 'state' => 'Tamil Nadu'],
    'thirukkuvalai' => ['name' => 'Thirukkuvalai', 'state' => 'Tamil Nadu'],
    'kolli-hills' => ['name' => 'Kolli Hills', 'state' => 'Tamil Nadu'],
    'sendamangalam' => ['name' => 'Sendamangalam', 'state' => 'Tamil Nadu'],
    'kumarapalayam' => ['name' => 'Kumarapalayam', 'state' => 'Tamil Nadu'],
    'paramathi-velur' => ['name' => 'Paramathi Velur', 'state' => 'Tamil Nadu'],
    'coonoor' => ['name' => 'Coonoor', 'state' => 'Tamil Nadu'],
    'kotagiri' => ['name' => 'Kotagiri', 'state' => 'Tamil Nadu'],
    'pandalur' => ['name' => 'Pandalur', 'state' => 'Tamil Nadu'],
    'kundah' => ['name' => 'Kundah', 'state' => 'Tamil Nadu'],
    'alathur' => ['name' => 'Alathur', 'state' => 'Tamil Nadu'],
    'kunnam' => ['name' => 'Kunnam', 'state' => 'Tamil Nadu'],
    'veppanthattai' => ['name' => 'Veppanthattai', 'state' => 'Tamil Nadu'],
    'avudayarkoil' => ['name' => 'Avudayarkoil', 'state' => 'Tamil Nadu'],
    'manamelkudi' => ['name' => 'Manamelkudi', 'state' => 'Tamil Nadu'],
    'illuppur' => ['name' => 'Illuppur', 'state' => 'Tamil Nadu'],
    'kulathur' => ['name' => 'Kulathur', 'state' => 'Tamil Nadu'],
    'ponnamaravathy' => ['name' => 'Ponnamaravathy', 'state' => 'Tamil Nadu'],
    'viralimalai' => ['name' => 'Viralimalai', 'state' => 'Tamil Nadu'],
    'alangudi' => ['name' => 'Alangudi', 'state' => 'Tamil Nadu'],
    'gandharvakottai' => ['name' => 'Gandharvakottai', 'state' => 'Tamil Nadu'],
    'karambakudi' => ['name' => 'Karambakudi', 'state' => 'Tamil Nadu'],
    'thirumayam' => ['name' => 'Thirumayam', 'state' => 'Tamil Nadu'],
    'kadaladi' => ['name' => 'Kadaladi', 'state' => 'Tamil Nadu'],
    'kamuthi' => ['name' => 'Kamuthi', 'state' => 'Tamil Nadu'],
    'mudukulathur' => ['name' => 'Mudukulathur', 'state' => 'Tamil Nadu'],
    'keelakarai' => ['name' => 'Keelakarai', 'state' => 'Tamil Nadu'],
    'nemili' => ['name' => 'Nemili', 'state' => 'Tamil Nadu'],
    'kalavai' => ['name' => 'Kalavai', 'state' => 'Tamil Nadu'],
    'walajah' => ['name' => 'Walajah', 'state' => 'Tamil Nadu'],
    'gangavalli' => ['name' => 'Gangavalli', 'state' => 'Tamil Nadu'],
    'pethanaickenpalayam' => ['name' => 'Pethanaickenpalayam', 'state' => 'Tamil Nadu'],
    'thalaivasal' => ['name' => 'Thalaivasal', 'state' => 'Tamil Nadu'],
    'kadayampatti' => ['name' => 'Kadayampatti', 'state' => 'Tamil Nadu'],
    'omalur' => ['name' => 'Omalur', 'state' => 'Tamil Nadu'],
    'salem-south' => ['name' => 'Salem South', 'state' => 'Tamil Nadu'],
    'salem-west' => ['name' => 'Salem West', 'state' => 'Tamil Nadu'],
    'valapady' => ['name' => 'Valapady', 'state' => 'Tamil Nadu'],
    'yercaud' => ['name' => 'Yercaud', 'state' => 'Tamil Nadu'],
    'sankari' => ['name' => 'Sankari', 'state' => 'Tamil Nadu'],
    'singampunari' => ['name' => 'Singampunari', 'state' => 'Tamil Nadu'],
    'ilayangudi' => ['name' => 'Ilayangudi', 'state' => 'Tamil Nadu'],
    'kalaiyarkoil' => ['name' => 'Kalaiyarkoil', 'state' => 'Tamil Nadu'],
    'thiruppuvanam' => ['name' => 'Thiruppuvanam', 'state' => 'Tamil Nadu'],
    'sivagiri' => ['name' => 'Sivagiri', 'state' => 'Tamil Nadu'],
    'thiruvengadam' => ['name' => 'Thiruvengadam', 'state' => 'Tamil Nadu'],
    'alangulam' => ['name' => 'Alangulam', 'state' => 'Tamil Nadu'],
    'shenkottai' => ['name' => 'Shenkottai', 'state' => 'Tamil Nadu'],
    'v.k.-pudur' => ['name' => 'V.K. Pudur', 'state' => 'Tamil Nadu'],
    'ettayapuram' => ['name' => 'Ettayapuram', 'state' => 'Tamil Nadu'],
    'kayathar' => ['name' => 'Kayathar', 'state' => 'Tamil Nadu'],
    'ottapidaram' => ['name' => 'Ottapidaram', 'state' => 'Tamil Nadu'],
    'vilathikulam' => ['name' => 'Vilathikulam', 'state' => 'Tamil Nadu'],
    'srivaikuntam' => ['name' => 'Srivaikuntam', 'state' => 'Tamil Nadu'],
    'eral' => ['name' => 'Eral', 'state' => 'Tamil Nadu'],
    'sattankulam' => ['name' => 'Sattankulam', 'state' => 'Tamil Nadu'],
    'cheranmahadevi' => ['name' => 'Cheranmahadevi', 'state' => 'Tamil Nadu'],
    'nanguneri' => ['name' => 'Nanguneri', 'state' => 'Tamil Nadu'],
    'radhapuram' => ['name' => 'Radhapuram', 'state' => 'Tamil Nadu'],
    'thisayanvilai' => ['name' => 'Thisayanvilai', 'state' => 'Tamil Nadu'],
    'manur' => ['name' => 'Manur', 'state' => 'Tamil Nadu'],
    'palayamkottai' => ['name' => 'Palayamkottai', 'state' => 'Tamil Nadu'],
    'kangayam' => ['name' => 'Kangayam', 'state' => 'Tamil Nadu'],
    'tiruppur-north' => ['name' => 'Tiruppur North', 'state' => 'Tamil Nadu'],
    'tiruppur-south' => ['name' => 'Tiruppur South', 'state' => 'Tamil Nadu'],
    'uthukuli' => ['name' => 'Uthukuli', 'state' => 'Tamil Nadu'],
    'madathukulam' => ['name' => 'Madathukulam', 'state' => 'Tamil Nadu'],
    'udumalpet' => ['name' => 'Udumalpet', 'state' => 'Tamil Nadu'],
    'gummidipoondi' => ['name' => 'Gummidipoondi', 'state' => 'Tamil Nadu'],
    'pallipattu' => ['name' => 'Pallipattu', 'state' => 'Tamil Nadu'],
    'r.k.-pettai' => ['name' => 'R.K. Pettai', 'state' => 'Tamil Nadu'],
    'poonamallee' => ['name' => 'Poonamallee', 'state' => 'Tamil Nadu'],
    'uthukottai' => ['name' => 'Uthukottai', 'state' => 'Tamil Nadu'],
    'jamunamarathur' => ['name' => 'Jamunamarathur', 'state' => 'Tamil Nadu'],
    'kalasapakkam' => ['name' => 'Kalasapakkam', 'state' => 'Tamil Nadu'],
    'chetpet' => ['name' => 'Chetpet', 'state' => 'Tamil Nadu'],
    'cheyyar' => ['name' => 'Cheyyar', 'state' => 'Tamil Nadu'],
    'vandavasi' => ['name' => 'Vandavasi', 'state' => 'Tamil Nadu'],
    'vembakkam' => ['name' => 'Vembakkam', 'state' => 'Tamil Nadu'],
    'kilpennathur' => ['name' => 'Kilpennathur', 'state' => 'Tamil Nadu'],
    'thandrampet' => ['name' => 'Thandrampet', 'state' => 'Tamil Nadu'],
    'k.v.-kuppam' => ['name' => 'K.V. Kuppam', 'state' => 'Tamil Nadu'],
    'anaicut' => ['name' => 'Anaicut', 'state' => 'Tamil Nadu'],
    'katpadi' => ['name' => 'Katpadi', 'state' => 'Tamil Nadu'],
    'gingee' => ['name' => 'Gingee', 'state' => 'Tamil Nadu'],
    'marakkanam' => ['name' => 'Marakkanam', 'state' => 'Tamil Nadu'],
    'melmalayanur' => ['name' => 'Melmalayanur', 'state' => 'Tamil Nadu'],
    'kandachipuram' => ['name' => 'Kandachipuram', 'state' => 'Tamil Nadu'],
    'tiruvennainallur' => ['name' => 'Tiruvennainallur', 'state' => 'Tamil Nadu'],
    'vanur' => ['name' => 'Vanur', 'state' => 'Tamil Nadu'],
    'vikravandi' => ['name' => 'Vikravandi', 'state' => 'Tamil Nadu'],
    'kariyapatti' => ['name' => 'Kariyapatti', 'state' => 'Tamil Nadu'],
    'tiruchuli' => ['name' => 'Tiruchuli', 'state' => 'Tamil Nadu'],
    'vembakkottai' => ['name' => 'Vembakkottai', 'state' => 'Tamil Nadu'],
    'watrap' => ['name' => 'Watrap', 'state' => 'Tamil Nadu']
];

// New list of cities/districts/states from the user's request
$newCities = [
    'nicobar' => ['name' => 'Nicobar', 'state' => 'Andaman and Nicobar Islands'],
    'north-middle-andaman' => ['name' => 'North Middle Andaman', 'state' => 'Andaman and Nicobar Islands'],
    'south-andaman' => ['name' => 'South Andaman', 'state' => 'Andaman and Nicobar Islands'],
    'alluri-sitarama-raju' => ['name' => 'Alluri Sitarama Raju', 'state' => 'Andhra Pradesh'],
    'anakapalli' => ['name' => 'Anakapalli', 'state' => 'Andhra Pradesh'],
    'anantapur' => ['name' => 'Anantapur', 'state' => 'Andhra Pradesh'],
    'annamaya' => ['name' => 'Annamaya', 'state' => 'Andhra Pradesh'],
    'bapatla' => ['name' => 'Bapatla', 'state' => 'Andhra Pradesh'],
    'chittoor' => ['name' => 'Chittoor', 'state' => 'Andhra Pradesh'],
    'east-godavari' => ['name' => 'East Godavari', 'state' => 'Andhra Pradesh'],
    'eluru' => ['name' => 'Eluru', 'state' => 'Andhra Pradesh'],
    'guntur' => ['name' => 'Guntur', 'state' => 'Andhra Pradesh'],
    'kadapa' => ['name' => 'Kadapa', 'state' => 'Andhra Pradesh'],
    'kakinada' => ['name' => 'Kakinada', 'state' => 'Andhra Pradesh'],
    'konaseema' => ['name' => 'Konaseema', 'state' => 'Andhra Pradesh'],
    'krishna' => ['name' => 'Krishna', 'state' => 'Andhra Pradesh'],
    'kurnool' => ['name' => 'Kurnool', 'state' => 'Andhra Pradesh'],
    'manyam' => ['name' => 'Manyam', 'state' => 'Andhra Pradesh'],
    'n-t-rama-rao' => ['name' => 'N T Rama Rao', 'state' => 'Andhra Pradesh'],
    'nandyal' => ['name' => 'Nandyal', 'state' => 'Andhra Pradesh'],
    'nellore' => ['name' => 'Nellore', 'state' => 'Andhra Pradesh'],
    'palnadu' => ['name' => 'Palnadu', 'state' => 'Andhra Pradesh'],
    'prakasam' => ['name' => 'Prakasam', 'state' => 'Andhra Pradesh'],
    'sri-balaji' => ['name' => 'Sri Balaji', 'state' => 'Andhra Pradesh'],
    'sri-satya-sai' => ['name' => 'Sri Satya Sai', 'state' => 'Andhra Pradesh'],
    'srikakulam' => ['name' => 'Srikakulam', 'state' => 'Andhra Pradesh'],
    'visakhapatnam' => ['name' => 'Visakhapatnam', 'state' => 'Andhra Pradesh'],
    'vizianagaram' => ['name' => 'Vizianagaram', 'state' => 'Andhra Pradesh'],
    'west-godavari' => ['name' => 'West Godavari', 'state' => 'Andhra Pradesh'],
    'anjaw' => ['name' => 'Anjaw', 'state' => 'Arunachal Pradesh'],
    'bichom' => ['name' => 'Bichom', 'state' => 'Arunachal Pradesh'],
    'changlang' => ['name' => 'Changlang', 'state' => 'Arunachal Pradesh'],
    'dibang-valley' => ['name' => 'Dibang Valley', 'state' => 'Arunachal Pradesh'],
    'east-kameng' => ['name' => 'East Kameng', 'state' => 'Arunachal Pradesh'],
    'east-siang' => ['name' => 'East Siang', 'state' => 'Arunachal Pradesh'],
    'kamle' => ['name' => 'Kamle', 'state' => 'Arunachal Pradesh'],
    'keyi-panyor' => ['name' => 'Keyi Panyor', 'state' => 'Arunachal Pradesh'],
    'kra-daadi' => ['name' => 'Kra Daadi', 'state' => 'Arunachal Pradesh'],
    'kurung-kumey' => ['name' => 'Kurung Kumey', 'state' => 'Arunachal Pradesh'],
    'lepa-rada' => ['name' => 'Lepa Rada', 'state' => 'Arunachal Pradesh'],
    'lohit' => ['name' => 'Lohit', 'state' => 'Arunachal Pradesh'],
    'longding' => ['name' => 'Longding', 'state' => 'Arunachal Pradesh'],
    'lower-dibang-valley' => ['name' => 'Lower Dibang Valley', 'state' => 'Arunachal Pradesh'],
    'lower-siang' => ['name' => 'Lower Siang', 'state' => 'Arunachal Pradesh'],
    'lower-subansiri' => ['name' => 'Lower Subansiri', 'state' => 'Arunachal Pradesh'],
    'namsai' => ['name' => 'Namsai', 'state' => 'Arunachal Pradesh'],
    'pakke-kessang' => ['name' => 'Pakke Kessang', 'state' => 'Arunachal Pradesh'],
    'papum-pare' => ['name' => 'Papum Pare', 'state' => 'Arunachal Pradesh'],
    'shi-yomi' => ['name' => 'Shi Yomi', 'state' => 'Arunachal Pradesh'],
    'siang' => ['name' => 'Siang', 'state' => 'Arunachal Pradesh'],
    'tawang' => ['name' => 'Tawang', 'state' => 'Arunachal Pradesh'],
    'tirap' => ['name' => 'Tirap', 'state' => 'Arunachal Pradesh'],
    'upper-siang' => ['name' => 'Upper Siang', 'state' => 'Arunachal Pradesh'],
    'upper-subansiri' => ['name' => 'Upper Subansiri', 'state' => 'Arunachal Pradesh'],
    'west-kameng' => ['name' => 'West Kameng', 'state' => 'Arunachal Pradesh'],
    'west-siang' => ['name' => 'West Siang', 'state' => 'Arunachal Pradesh'],
    'bajali' => ['name' => 'Bajali', 'state' => 'Assam'],
    'baksa' => ['name' => 'Baksa', 'state' => 'Assam'],
    'barpeta' => ['name' => 'Barpeta', 'state' => 'Assam'],
    'biswanath' => ['name' => 'Biswanath', 'state' => 'Assam'],
    'bongaigaon' => ['name' => 'Bongaigaon', 'state' => 'Assam'],
    'cachar' => ['name' => 'Cachar', 'state' => 'Assam'],
    'charaideo' => ['name' => 'Charaideo', 'state' => 'Assam'],
    'chirang' => ['name' => 'Chirang', 'state' => 'Assam'],
    'darrang' => ['name' => 'Darrang', 'state' => 'Assam'],
    'dhemaji' => ['name' => 'Dhemaji', 'state' => 'Assam'],
    'dhubri' => ['name' => 'Dhubri', 'state' => 'Assam'],
    'dibrugarh' => ['name' => 'Dibrugarh', 'state' => 'Assam'],
    'dima-haso' => ['name' => 'Dima Hasao', 'state' => 'Assam'],
    'goalpara' => ['name' => 'Goalpara', 'state' => 'Assam'],
    'golaghat' => ['name' => 'Golaghat', 'state' => 'Assam'],
    'hailakandi' => ['name' => 'Hailakandi', 'state' => 'Assam'],
    'hojai' => ['name' => 'Hojai', 'state' => 'Assam'],
    'jorhat' => ['name' => 'Jorhat', 'state' => 'Assam'],
    'kamrup-metropolitan' => ['name' => 'Kamrup Metropolitan', 'state' => 'Assam'],
    'kamrup-rural' => ['name' => 'Kamrup Rural', 'state' => 'Assam'],
    'karbi-anglong' => ['name' => 'Karbi Anglong', 'state' => 'Assam'],
    'karimganj' => ['name' => 'Karimganj', 'state' => 'Assam'],
    'kokrajhar' => ['name' => 'Kokrajhar', 'state' => 'Assam'],
    'lakhimpur' => ['name' => 'Lakhimpur', 'state' => 'Assam'],
    'majuli' => ['name' => 'Majuli', 'state' => 'Assam'],
    'morigaon' => ['name' => 'Morigaon', 'state' => 'Assam'],
    'nagaon' => ['name' => 'Nagaon', 'state' => 'Assam'],
    'nalbari' => ['name' => 'Nalbari', 'state' => 'Assam'],
    'sivasagar' => ['name' => 'Sivasagar', 'state' => 'Assam'],
    'sonitpur' => ['name' => 'Sonitpur', 'state' => 'Assam'],
    'south-salmara-mankachar' => ['name' => 'South Salmara-Mankachar', 'state' => 'Assam'],
    'tamulpur' => ['name' => 'Tamulpur', 'state' => 'Assam'],
    'tinsukia' => ['name' => 'Tinsukia', 'state' => 'Assam'],
    'udalguri' => ['name' => 'Udalguri', 'state' => 'Assam'],
    'west-karbi-anglong' => ['name' => 'West Karbi Anglong', 'state' => 'Assam'],
    'araria' => ['name' => 'Araria', 'state' => 'Bihar'],
    'arwal' => ['name' => 'Arwal', 'state' => 'Bihar'],
    'aurangabad' => ['name' => 'Aurangabad', 'state' => 'Bihar'],
    'banka' => ['name' => 'Banka', 'state' => 'Bihar'],
    'begusarai' => ['name' => 'Begusarai', 'state' => 'Bihar'],
    'bhagalpur' => ['name' => 'Bhagalpur', 'state' => 'Bihar'],
    'bhojpur' => ['name' => 'Bhojpur', 'state' => 'Bihar'],
    'buxar' => ['name' => 'Buxar', 'state' => 'Bihar'],
    'darbhanga' => ['name' => 'Darbhanga', 'state' => 'Bihar'],
    'east-champaran' => ['name' => 'East Champaran', 'state' => 'Bihar'],
    'gaya' => ['name' => 'Gaya', 'state' => 'Bihar'],
    'gopalganj' => ['name' => 'Gopalganj', 'state' => 'Bihar'],
    'jamui' => ['name' => 'Jamui', 'state' => 'Bihar'],
    'jehanabad' => ['name' => 'Jehanabad', 'state' => 'Bihar'],
    'kaimur' => ['name' => 'Kaimur', 'state' => 'Bihar'],
    'katihar' => ['name' => 'Katihar', 'state' => 'Bihar'],
    'khagaria' => ['name' => 'Khagaria', 'state' => 'Bihar'],
    'kishanganj' => ['name' => 'Kishanganj', 'state' => 'Bihar'],
    'lakhisarai' => ['name' => 'Lakhisarai', 'state' => 'Bihar'],
    'madhepura' => ['name' => 'Madhepura', 'state' => 'Bihar'],
    'madhubani' => ['name' => 'Madhubani', 'state' => 'Bihar'],
    'munger' => ['name' => 'Munger', 'state' => 'Bihar'],
    'muzaffarpur' => ['name' => 'Muzaffarpur', 'state' => 'Bihar'],
    'nalanda' => ['name' => 'Nalanda', 'state' => 'Bihar'],
    'nawada' => ['name' => 'Nawada', 'state' => 'Bihar'],
    'patna' => ['name' => 'Patna', 'state' => 'Bihar'],
    'purnia' => ['name' => 'Purnia', 'state' => 'Bihar'],
    'rohtas' => ['name' => 'Rohtas', 'state' => 'Bihar'],
    'saharsa' => ['name' => 'Saharsa', 'state' => 'Bihar'],
    'samastipur' => ['name' => 'Samastipur', 'state' => 'Bihar'],
    'saran' => ['name' => 'Saran', 'state' => 'Bihar'],
    'sheikhpura' => ['name' => 'Sheikhpura', 'state' => 'Bihar'],
    'sheohar' => ['name' => 'Sheohar', 'state' => 'Bihar'],
    'sitamarhi' => ['name' => 'Sitamarhi', 'state' => 'Bihar'],
    'siwan' => ['name' => 'Siwan', 'state' => 'Bihar'],
    'supaul' => ['name' => 'Supaul', 'state' => 'Bihar'],
    'vaishali' => ['name' => 'Vaishali', 'state' => 'Bihar'],
    'west-champaran' => ['name' => 'West Champaran', 'state' => 'Bihar'],
    'central-delhi' => ['name' => 'Central Delhi', 'state' => 'Delhi'],
    'east-delhi' => ['name' => 'East Delhi', 'state' => 'Delhi'],
    'new-delhi' => ['name' => 'New Delhi', 'state' => 'Delhi'],
    'north-delhi' => ['name' => 'North Delhi', 'state' => 'Delhi'],
    'north-east-delhi' => ['name' => 'North East Delhi', 'state' => 'Delhi'],
    'north-west-delhi' => ['name' => 'North West Delhi', 'state' => 'Delhi'],
    'shahdara' => ['name' => 'Shahdara', 'state' => 'Delhi'],
    'south-delhi' => ['name' => 'South Delhi', 'state' => 'Delhi'],
    'south-east-delhi' => ['name' => 'South East Delhi', 'state' => 'Delhi'],
    'south-west-delhi' => ['name' => 'South West Delhi', 'state' => 'Delhi'],
    'west-delhi' => ['name' => 'West Delhi', 'state' => 'Delhi'],
    'north-goa' => ['name' => 'North Goa', 'state' => 'Goa'],
    'south-goa' => ['name' => 'South Goa', 'state' => 'Goa'],
    'ahmedabad' => ['name' => 'Ahmedabad', 'state' => 'Gujarat'],
    'amreli' => ['name' => 'Amreli', 'state' => 'Gujarat'],
    'anand' => ['name' => 'Anand', 'state' => 'Gujarat'],
    'aravalli' => ['name' => 'Aravalli', 'state' => 'Gujarat'],
    'banaskantha' => ['name' => 'Banaskantha', 'state' => 'Gujarat'],
    'bharuch' => ['name' => 'Bharuch', 'state' => 'Gujarat'],
    'bhavnagar' => ['name' => 'Bhavnagar', 'state' => 'Gujarat'],
    'botad' => ['name' => 'Botad', 'state' => 'Gujarat'],
    'chhota-udaipur' => ['name' => 'Chhota Udaipur', 'state' => 'Gujarat'],
    'dahod' => ['name' => 'Dahod', 'state' => 'Gujarat'],
    'dang' => ['name' => 'Dang', 'state' => 'Gujarat'],
    'devbhoomi-dwarka' => ['name' => 'Devbhoomi Dwarka', 'state' => 'Gujarat'],
    'gandhinagar' => ['name' => 'Gandhinagar', 'state' => 'Gujarat'],
    'gir-somnath' => ['name' => 'Gir Somnath', 'state' => 'Gujarat'],
    'jamnagar' => ['name' => 'Jamnagar', 'state' => 'Gujarat'],
    'junagadh' => ['name' => 'Junagadh', 'state' => 'Gujarat'],
    'kheda' => ['name' => 'Kheda', 'state' => 'Gujarat'],
    'kutch' => ['name' => 'Kutch', 'state' => 'Gujarat'],
    'mahisagar' => ['name' => 'Mahisagar', 'state' => 'Gujarat'],
    'mehsana' => ['name' => 'Mehsana', 'state' => 'Gujarat'],
    'morbi' => ['name' => 'Morbi', 'state' => 'Gujarat'],
    'narmada' => ['name' => 'Narmada', 'state' => 'Gujarat'],
    'navsari' => ['name' => 'Navsari', 'state' => 'Gujarat'],
    'panchmahal' => ['name' => 'Panchmahal', 'state' => 'Gujarat'],
    'patan' => ['name' => 'Patan', 'state' => 'Gujarat'],
    'porbandar' => ['name' => 'Porbandar', 'state' => 'Gujarat'],
    'rajkot' => ['name' => 'Rajkot', 'state' => 'Gujarat'],
    'sabarkantha' => ['name' => 'Sabarkantha', 'state' => 'Gujarat'],
    'surat' => ['name' => 'Surat', 'state' => 'Gujarat'],
    'surendranagar' => ['name' => 'Surendranagar', 'state' => 'Gujarat'],
    'tapi' => ['name' => 'Tapi', 'state' => 'Gujarat'],
    'vadodara' => ['name' => 'Vadodara', 'state' => 'Gujarat'],
    'valsad' => ['name' => 'Valsad', 'state' => 'Gujarat'],
    'ambala' => ['name' => 'Ambala', 'state' => 'Haryana'],
    'bhiwani' => ['name' => 'Bhiwani', 'state' => 'Haryana'],
    'charkhi-dadri' => ['name' => 'Charkhi Dadri', 'state' => 'Haryana'],
    'faridabad' => ['name' => 'Faridabad', 'state' => 'Haryana'],
    'fatehabad' => ['name' => 'Fatehabad', 'state' => 'Haryana'],
    'gurugram' => ['name' => 'Gurugram', 'state' => 'Haryana'],
    'hisar' => ['name' => 'Hisar', 'state' => 'Haryana'],
    'jhajjar' => ['name' => 'Jhajjar', 'state' => 'Haryana'],
    'jind' => ['name' => 'Jind', 'state' => 'Haryana'],
    'kaithal' => ['name' => 'Kaithal', 'state' => 'Haryana'],
    'karnal' => ['name' => 'Karnal', 'state' => 'Haryana'],
    'kurukshetra' => ['name' => 'Kurukshetra', 'state' => 'Haryana'],
    'mahendragarh' => ['name' => 'Mahendragarh', 'state' => 'Haryana'],
    'nuh' => ['name' => 'Nuh', 'state' => 'Haryana'],
    'palwal' => ['name' => 'Palwal', 'state' => 'Haryana'],
    'panchkula' => ['name' => 'Panchkula', 'state' => 'Haryana'],
    'panipat' => ['name' => 'Panipat', 'state' => 'Haryana'],
    'rewari' => ['name' => 'Rewari', 'state' => 'Haryana'],
    'rohtak' => ['name' => 'Rohtak', 'state' => 'Haryana'],
    'sirsa' => ['name' => 'Sirsa', 'state' => 'Haryana'],
    'sonipat' => ['name' => 'Sonipat', 'state' => 'Haryana'],
    'yamunanagar' => ['name' => 'Yamunanagar', 'state' => 'Haryana'],
    'chamba' => ['name' => 'Chamba', 'state' => 'Himachal Pradesh'],
    'hamirpur' => ['name' => 'Hamirpur', 'state' => 'Himachal Pradesh'],
    'kangra' => ['name' => 'Kangra', 'state' => 'Himachal Pradesh'],
    'kinnaur' => ['name' => 'Kinnaur', 'state' => 'Himachal Pradesh'],
    'kullu' => ['name' => 'Kullu', 'state' => 'Himachal Pradesh'],
    'lahaul-spiti' => ['name' => 'Lahaul Spiti', 'state' => 'Himachal Pradesh'],
    'mandi' => ['name' => 'Mandi', 'state' => 'Himachal Pradesh'],
    'shimla' => ['name' => 'Shimla', 'state' => 'Himachal Pradesh'],
    'sirmaur' => ['name' => 'Sirmaur', 'state' => 'Himachal Pradesh'],
    'solan' => ['name' => 'Solan', 'state' => 'Himachal Pradesh'],
    'una' => ['name' => 'Una', 'state' => 'Himachal Pradesh'],
    'anantnag' => ['name' => 'Anantnag', 'state' => 'Jammu and Kashmir'],
    'bandipora' => ['name' => 'Bandipora', 'state' => 'Jammu and Kashmir'],
    'baramulla' => ['name' => 'Baramulla', 'state' => 'Jammu and Kashmir'],
    'budgam' => ['name' => 'Budgam', 'state' => 'Jammu and Kashmir'],
    'doda' => ['name' => 'Doda', 'state' => 'Jammu and Kashmir'],
    'ganderbal' => ['name' => 'Ganderbal', 'state' => 'Jammu and Kashmir'],
    'jammu' => ['name' => 'Jammu', 'state' => 'Jammu and Kashmir'],
    'kathua' => ['name' => 'Kathua', 'state' => 'Jammu and Kashmir'],
    'kishtwar' => ['name' => 'Kishtwar', 'state' => 'Jammu and Kashmir'],
    'kulgam' => ['name' => 'Kulgam', 'state' => 'Jammu and Kashmir'],
    'kupwara' => ['name' => 'Kupwara', 'state' => 'Jammu and Kashmir'],
    'poonch' => ['name' => 'Poonch', 'state' => 'Jammu and Kashmir'],
    'pulwama' => ['name' => 'Pulwama', 'state' => 'Jammu and Kashmir'],
    'rajouri' => ['name' => 'Rajouri', 'state' => 'Jammu and Kashmir'],
    'ramban' => ['name' => 'Ramban', 'state' => 'Jammu and Kashmir'],
    'reasi' => ['name' => 'Reasi', 'state' => 'Jammu and Kashmir'],
    'samba' => ['name' => 'Samba', 'state' => 'Jammu and Kashmir'],
    'shopian' => ['name' => 'Shopian', 'state' => 'Jammu and Kashmir'],
    'srinagar' => ['name' => 'Srinagar', 'state' => 'Jammu and Kashmir'],
    'udhampur' => ['name' => 'Udhampur', 'state' => 'Jammu and Kashmir'],
    'bokaro' => ['name' => 'Bokaro', 'state' => 'Jharkhand'],
    'chatra' => ['name' => 'Chatra', 'state' => 'Jharkhand'],
    'deoghar' => ['name' => 'Deoghar', 'state' => 'Jharkhand'],
    'dhanbad' => ['name' => 'Dhanbad', 'state' => 'Jharkhand'],
    'dumka' => ['name' => 'Dumka', 'state' => 'Jharkhand'],
    'east-singhbhum' => ['name' => 'East Singhbhum', 'state' => 'Jharkhand'],
    'garhwa' => ['name' => 'Garhwa', 'state' => 'Jharkhand'],
    'giridih' => ['name' => 'Giridih', 'state' => 'Jharkhand'],
    'godda' => ['name' => 'Godda', 'state' => 'Jharkhand'],
    'gumla' => ['name' => 'Gumla', 'state' => 'Jharkhand'],
    'hazaribagh' => ['name' => 'Hazaribagh', 'state' => 'Jharkhand'],
    'jamtara' => ['name' => 'Jamtara', 'state' => 'Jharkhand'],
    'khunti' => ['name' => 'Khunti', 'state' => 'Jharkhand'],
    'koderma' => ['name' => 'Koderma', 'state' => 'Jharkhand'],
    'latehar' => ['name' => 'Latehar', 'state' => 'Jharkhand'],
    'lohardaga' => ['name' => 'Lohardaga', 'state' => 'Jharkhand'],
    'pakur' => ['name' => 'Pakur', 'state' => 'Jharkhand'],
    'palamu' => ['name' => 'Palamu', 'state' => 'Jharkhand'],
    'ramgarh' => ['name' => 'Ramgarh', 'state' => 'Jharkhand'],
    'ranchi' => ['name' => 'Ranchi', 'state' => 'Jharkhand'],
    'sahebganj' => ['name' => 'Sahebganj', 'state' => 'Jharkhand'],
    'seraikela-kharsawan' => ['name' => 'Seraikela Kharsawan', 'state' => 'Jharkhand'],
    'simdega' => ['name' => 'Simdega', 'state' => 'Jharkhand'],
    'west-singhbhum' => ['name' => 'West Singhbhum', 'state' => 'Jharkhand'],
    'bagalkot' => ['name' => 'Bagalkot', 'state' => 'Karnataka'],
    'bangalore-rural' => ['name' => 'Bangalore Rural', 'state' => 'Karnataka'],
    'bangalore-urban' => ['name' => 'Bangalore Urban', 'state' => 'Karnataka'],
    'belgaum' => ['name' => 'Belgaum', 'state' => 'Karnataka'],
    'bellary' => ['name' => 'Bellary', 'state' => 'Karnataka'],
    'bidar' => ['name' => 'Bidar', 'state' => 'Karnataka'],
    'chamarajanagar' => ['name' => 'Chamarajanagar', 'state' => 'Karnataka'],
    'chikkaballapur' => ['name' => 'Chikkaballapur', 'state' => 'Karnataka'],
    'chikkamagaluru' => ['name' => 'Chikkamagaluru', 'state' => 'Karnataka'],
    'chitradurga' => ['name' => 'Chitradurga', 'state' => 'Karnataka'],
    'dakshina-kannada' => ['name' => 'Dakshina Kannada', 'state' => 'Karnataka'],
    'davanagere' => ['name' => 'Davanagere', 'state' => 'Karnataka'],
    'dharwad' => ['name' => 'Dharwad', 'state' => 'Karnataka'],
    'gadag' => ['name' => 'Gadag', 'state' => 'Karnataka'],
    'hassan' => ['name' => 'Hassan', 'state' => 'Karnataka'],
    'haveri' => ['name' => 'Haveri', 'state' => 'Karnataka'],
    'kalaburagi' => ['name' => 'Kalaburagi', 'state' => 'Karnataka'],
    'kodagu' => ['name' => 'Kodagu', 'state' => 'Karnataka'],
    'kolar' => ['name' => 'Kolar', 'state' => 'Karnataka'],
    'koppal' => ['name' => 'Koppal', 'state' => 'Karnataka'],
    'mandya' => ['name' => 'Mandya', 'state' => 'Karnataka'],
    'mysore' => ['name' => 'Mysore', 'state' => 'Karnataka'],
    'raichur' => ['name' => 'Raichur', 'state' => 'Karnataka'],
    'ramanagara' => ['name' => 'Ramanagara', 'state' => 'Karnataka'],
    'shimoga' => ['name' => 'Shimoga', 'state' => 'Karnataka'],
    'tumkur' => ['name' => 'Tumkur', 'state' => 'Karnataka'],
    'udupi' => ['name' => 'Udupi', 'state' => 'Karnataka'],
    'uttara-kannada' => ['name' => 'Uttara Kannada', 'state' => 'Karnataka'],
    'vijayanagara' => ['name' => 'Vijayanagara', 'state' => 'Karnataka'],
    'vijayapura' => ['name' => 'Vijayapura', 'state' => 'Karnataka'],
    'yadgir' => ['name' => 'Yadgir', 'state' => 'Karnataka'],
    'alappuzha' => ['name' => 'Alappuzha', 'state' => 'Kerala'],
    'ernakulam' => ['name' => 'Ernakulam', 'state' => 'Kerala'],
    'idukki' => ['name' => 'Idukki', 'state' => 'Kerala'],
    'kannur' => ['name' => 'Kannur', 'state' => 'Kerala'],
    'kasaragod' => ['name' => 'Kasaragod', 'state' => 'Kerala'],
    'kollam' => ['name' => 'Kollam', 'state' => 'Kerala'],
    'kottayam' => ['name' => 'Kottayam', 'state' => 'Kerala'],
    'kozhikode' => ['name' => 'Kozhikode', 'state' => 'Kerala'],
    'malappuram' => ['name' => 'Malappuram', 'state' => 'Kerala'],
    'palakkad' => ['name' => 'Palakkad', 'state' => 'Kerala'],
    'pathanamthitta' => ['name' => 'Pathanamthitta', 'state' => 'Kerala'],
    'thiruvananthapuram' => ['name' => 'Thiruvananthapuram', 'state' => 'Kerala'],
    'thrissur' => ['name' => 'Thrissur', 'state' => 'Kerala'],
    'wayanad' => ['name' => 'Wayanad', 'state' => 'Kerala'],
    'kargil' => ['name' => 'Kargil', 'state' => 'Ladakh'],
    'leh' => ['name' => 'Leh', 'state' => 'Ladakh'],
    'agare-malwa' => ['name' => 'Agar Malwa', 'state' => 'Madhya Pradesh'],
    'alirajpur' => ['name' => 'Alirajpur', 'state' => 'Madhya Pradesh'],
    'anuppur' => ['name' => 'Anuppur', 'state' => 'Madhya Pradesh'],
    'ashoknagar' => ['name' => 'Ashoknagar', 'state' => 'Madhya Pradesh'],
    'balaghat' => ['name' => 'Balaghat', 'state' => 'Madhya Pradesh'],
    'barwani' => ['name' => 'Barwani', 'state' => 'Madhya Pradesh'],
    'betul' => ['name' => 'Betul', 'state' => 'Madhya Pradesh'],
    'bhind' => ['name' => 'Bhind', 'state' => 'Madhya Pradesh'],
    'bhopal' => ['name' => 'Bhopal', 'state' => 'Madhya Pradesh'],
    'burhanpur' => ['name' => 'Burhanpur', 'state' => 'Madhya Pradesh'],
    'chhatarpur' => ['name' => 'Chhatarpur', 'state' => 'Madhya Pradesh'],
    'chhindwara' => ['name' => 'Chhindwara', 'state' => 'Madhya Pradesh'],
    'damoh' => ['name' => 'Damoh', 'state' => 'Madhya Pradesh'],
    'datia' => ['name' => 'Datia', 'state' => 'Madhya Pradesh'],
    'dewas' => ['name' => 'Dewas', 'state' => 'Madhya Pradesh'],
    'dhar' => ['name' => 'Dhar', 'state' => 'Madhya Pradesh'],
    'dindori' => ['name' => 'Dindori', 'state' => 'Madhya Pradesh'],
    'guna' => ['name' => 'Guna', 'state' => 'Madhya Pradesh'],
    'gwalior' => ['name' => 'Gwalior', 'state' => 'Madhya Pradesh'],
    'harda' => ['name' => 'Harda', 'state' => 'Madhya Pradesh'],
    'hoshangabad' => ['name' => 'Hoshangabad', 'state' => 'Madhya Pradesh'],
    'indore' => ['name' => 'Indore', 'state' => 'Madhya Pradesh'],
    'jabalpur' => ['name' => 'Jabalpur', 'state' => 'Madhya Pradesh'],
    'jhabua' => ['name' => 'Jhabua', 'state' => 'Madhya Pradesh'],
    'katni' => ['name' => 'Katni', 'state' => 'Madhya Pradesh'],
    'khandwa' => ['name' => 'Khandwa', 'state' => 'Madhya Pradesh'],
    'khargone' => ['name' => 'Khargone', 'state' => 'Madhya Pradesh'],
    'maihar' => ['name' => 'Maihar', 'state' => 'Madhya Pradesh'],
    'mandla' => ['name' => 'Mandla', 'state' => 'Madhya Pradesh'],
    'mandsaur' => ['name' => 'Mandsaur', 'state' => 'Madhya Pradesh'],
    'mauganj' => ['name' => 'Mauganj', 'state' => 'Madhya Pradesh'],
    'morena' => ['name' => 'Morena', 'state' => 'Madhya Pradesh'],
    'narsinghpur' => ['name' => 'Narsinghpur', 'state' => 'Madhya Pradesh'],
    'neemuch' => ['name' => 'Neemuch', 'state' => 'Madhya Pradesh'],
    'niwari' => ['name' => 'Niwari', 'state' => 'Madhya Pradesh'],
    'pandhurna' => ['name' => 'Pandhurna', 'state' => 'Madhya Pradesh'],
    'panna' => ['name' => 'Panna', 'state' => 'Madhya Pradesh'],
    'raisen' => ['name' => 'Raisen', 'state' => 'Madhya Pradesh'],
    'rajgarh' => ['name' => 'Rajgarh', 'state' => 'Madhya Pradesh'],
    'ratlam' => ['name' => 'Ratlam', 'state' => 'Madhya Pradesh'],
    'rewa' => ['name' => 'Rewa', 'state' => 'Madhya Pradesh'],
    'sagar' => ['name' => 'Sagar', 'state' => 'Madhya Pradesh'],
    'satna' => ['name' => 'Satna', 'state' => 'Madhya Pradesh'],
    'sehore' => ['name' => 'Sehore', 'state' => 'Madhya Pradesh'],
    'seoni' => ['name' => 'Seoni', 'state' => 'Madhya Pradesh'],
    'shahdol' => ['name' => 'Shahdol', 'state' => 'Madhya Pradesh'],
    'shajapur' => ['name' => 'Shajapur', 'state' => 'Madhya Pradesh'],
    'sheopur' => ['name' => 'Sheopur', 'state' => 'Madhya Pradesh'],
    'shivpuri' => ['name' => 'Shivpuri', 'state' => 'Madhya Pradesh'],
    'sidhi' => ['name' => 'Sidhi', 'state' => 'Madhya Pradesh'],
    'singrauli' => ['name' => 'Singrauli', 'state' => 'Madhya Pradesh'],
    'tikamgarh' => ['name' => 'Tikamgarh', 'state' => 'Madhya Pradesh'],
    'ujjain' => ['name' => 'Ujjain', 'state' => 'Madhya Pradesh'],
    'umaria' => ['name' => 'Umaria', 'state' => 'Madhya Pradesh'],
    'vidisha' => ['name' => 'Vidisha', 'state' => 'Madhya Pradesh'],
    'ahmednagar' => ['name' => 'Ahmednagar', 'state' => 'Maharashtra'],
    'akola' => ['name' => 'Akola', 'state' => 'Maharashtra'],
    'amravati' => ['name' => 'Amravati', 'state' => 'Maharashtra'],
    'beed' => ['name' => 'Beed', 'state' => 'Maharashtra'],
    'bhandara' => ['name' => 'Bhandara', 'state' => 'Maharashtra'],
    'buldhana' => ['name' => 'Buldhana', 'state' => 'Maharashtra'],
    'chandrapur' => ['name' => 'Chandrapur', 'state' => 'Maharashtra'],
    'dhule' => ['name' => 'Dhule', 'state' => 'Maharashtra'],
    'gadchiroli' => ['name' => 'Gadchiroli', 'state' => 'Maharashtra'],
    'gondia' => ['name' => 'Gondia', 'state' => 'Maharashtra'],
    'hingoli' => ['name' => 'Hingoli', 'state' => 'Maharashtra'],
    'jalgaon' => ['name' => 'Jalgaon', 'state' => 'Maharashtra'],
    'jalna' => ['name' => 'Jalna', 'state' => 'Maharashtra'],
    'kolhapur' => ['name' => 'Kolhapur', 'state' => 'Maharashtra'],
    'latur' => ['name' => 'Latur', 'state' => 'Maharashtra'],
    'mumbai-city' => ['name' => 'Mumbai City', 'state' => 'Maharashtra'],
    'mumbai-suburban' => ['name' => 'Mumbai Suburban', 'state' => 'Maharashtra'],
    'nagpur' => ['name' => 'Nagpur', 'state' => 'Maharashtra'],
    'nanded' => ['name' => 'Nanded', 'state' => 'Maharashtra'],
    'nandurbar' => ['name' => 'Nandurbar', 'state' => 'Maharashtra'],
    'nashik' => ['name' => 'Nashik', 'state' => 'Maharashtra'],
    'osmanabad' => ['name' => 'Osmanabad', 'state' => 'Maharashtra'],
    'palghar' => ['name' => 'Palghar', 'state' => 'Maharashtra'],
    'parbhani' => ['name' => 'Parbhani', 'state' => 'Maharashtra'],
    'pune' => ['name' => 'Pune', 'state' => 'Maharashtra'],
    'raigad' => ['name' => 'Raigad', 'state' => 'Maharashtra'],
    'ratnagiri' => ['name' => 'Ratnagiri', 'state' => 'Maharashtra'],
    'sangli' => ['name' => 'Sangli', 'state' => 'Maharashtra'],
    'satara' => ['name' => 'Satara', 'state' => 'Maharashtra'],
    'sindhudurg' => ['name' => 'Sindhudurg', 'state' => 'Maharashtra'],
    'solapur' => ['name' => 'Solapur', 'state' => 'Maharashtra'],
    'thane' => ['name' => 'Thane', 'state' => 'Maharashtra'],
    'wardha' => ['name' => 'Wardha', 'state' => 'Maharashtra'],
    'washim' => ['name' => 'Washim', 'state' => 'Maharashtra'],
    'yavatmal' => ['name' => 'Yavatmal', 'state' => 'Maharashtra'],
    'bishnupur' => ['name' => 'Bishnupur', 'state' => 'Manipur'],
    'chandel' => ['name' => 'Chandel', 'state' => 'Manipur'],
    'churachandpur' => ['name' => 'Churachandpur', 'state' => 'Manipur'],
    'imphal-east' => ['name' => 'Imphal East', 'state' => 'Manipur'],
    'imphal-west' => ['name' => 'Imphal West', 'state' => 'Manipur'],
    'jiribam' => ['name' => 'Jiribam', 'state' => 'Manipur'],
    'kakching' => ['name' => 'Kakching', 'state' => 'Manipur'],
    'kamjong' => ['name' => 'Kamjong', 'state' => 'Manipur'],
    'kangpokpi' => ['name' => 'Kangpokpi', 'state' => 'Manipur'],
    'noney' => ['name' => 'Noney', 'state' => 'Manipur'],
    'pherzawl' => ['name' => 'Pherzawl', 'state' => 'Manipur'],
    'senapati' => ['name' => 'Senapati', 'state' => 'Manipur'],
    'tamenglong' => ['name' => 'Tamenglong', 'state' => 'Manipur'],
    'tengnoupal' => ['name' => 'Tengnoupal', 'state' => 'Manipur'],
    'thoubal' => ['name' => 'Thoubal', 'state' => 'Manipur'],
    'ukhrul' => ['name' => 'Ukhrul', 'state' => 'Manipur'],
    'east-garo-hills' => ['name' => 'East Garo Hills', 'state' => 'Meghalaya'],
    'east-jaintia-hills' => ['name' => 'East Jaintia Hills', 'state' => 'Meghalaya'],
    'east-khasi-hills' => ['name' => 'East Khasi Hills', 'state' => 'Meghalaya'],
    'mairang' => ['name' => 'Mairang', 'state' => 'Meghalaya'],
    'north-garo-hills' => ['name' => 'North Garo Hills', 'state' => 'Meghalaya'],
    'ri-bhoi' => ['name' => 'Ri Bhoi', 'state' => 'Meghalaya'],
    'south-garo-hills' => ['name' => 'South Garo Hills', 'state' => 'Meghalaya'],
    'south-west-garo-hills' => ['name' => 'South West Garo Hills', 'state' => 'Meghalaya'],
    'south-west-khasi-hills' => ['name' => 'South West Khasi Hills', 'state' => 'Meghalaya'],
    'west-garo-hills' => ['name' => 'West Garo Hills', 'state' => 'Meghalaya'],
    'west-jaintia-hills' => ['name' => 'West Jaintia Hills', 'state' => 'Meghalaya'],
    'west-khasi-hills' => ['name' => 'West Khasi Hills', 'state' => 'Meghalaya'],
    'aizawl' => ['name' => 'Aizawl', 'state' => 'Mizoram'],
    'champhai' => ['name' => 'Champhai', 'state' => 'Mizoram'],
    'hnahthial' => ['name' => 'Hnahthial', 'state' => 'Mizoram'],
    'khawzawl' => ['name' => 'Khawzawl', 'state' => 'Mizoram'],
    'kolasib' => ['name' => 'Kolasib', 'state' => 'Mizoram'],
    'lawngtlai' => ['name' => 'Lawngtlai', 'state' => 'Mizoram'],
    'lunglei' => ['name' => 'Lunglei', 'state' => 'Mizoram'],
    'mamit' => ['name' => 'Mamit', 'state' => 'Mizoram'],
    'saiha' => ['name' => 'Saiha', 'state' => 'Mizoram'],
    'saitual' => ['name' => 'Saitual', 'state' => 'Mizoram'],
    'serchhip' => ['name' => 'Serchhip', 'state' => 'Mizoram'],
    'chumukedima' => ['name' => 'Chumukedima', 'state' => 'Nagaland'],
    'dimapur' => ['name' => 'Dimapur', 'state' => 'Nagaland'],
    'kiphire' => ['name' => 'Kiphire', 'state' => 'Nagaland'],
    'kohima' => ['name' => 'Kohima', 'state' => 'Nagaland'],
    'longleng' => ['name' => 'Longleng', 'state' => 'Nagaland'],
    'mokokchung' => ['name' => 'Mokokchung', 'state' => 'Nagaland'],
    'mon' => ['name' => 'Mon', 'state' => 'Nagaland'],
    'niuland' => ['name' => 'Niuland', 'state' => 'Nagaland'],
    'noklak' => ['name' => 'Noklak', 'state' => 'Nagaland'],
    'peren' => ['name' => 'Peren', 'state' => 'Nagaland'],
    'phek' => ['name' => 'Phek', 'state' => 'Nagaland'],
    'shamator' => ['name' => 'Shamator', 'state' => 'Nagaland'],
    'tseminyu' => ['name' => 'Tseminyu', 'state' => 'Nagaland'],
    'tuensang' => ['name' => 'Tuensang', 'state' => 'Nagaland'],
    'wokha' => ['name' => 'Wokha', 'state' => 'Nagaland'],
    'zunheboto' => ['name' => 'Zunheboto', 'state' => 'Nagaland'],
    'angul' => ['name' => 'Angul', 'state' => 'Odisha'],
    'balangir' => ['name' => 'Balangir', 'state' => 'Odisha'],
    'balasore' => ['name' => 'Balasore', 'state' => 'Odisha'],
    'bargarh' => ['name' => 'Bargarh', 'state' => 'Odisha'],
    'bhadrak' => ['name' => 'Bhadrak', 'state' => 'Odisha'],
    'boudh' => ['name' => 'Boudh', 'state' => 'Odisha'],
    'cuttack' => ['name' => 'Cuttack', 'state' => 'Odisha'],
    'debagarh' => ['name' => 'Debagarh', 'state' => 'Odisha'],
    'dhenkanal' => ['name' => 'Dhenkanal', 'state' => 'Odisha'],
    'gajapati' => ['name' => 'Gajapati', 'state' => 'Odisha'],
    'ganjam' => ['name' => 'Ganjam', 'state' => 'Odisha'],
    'jagatsinghpur' => ['name' => 'Jagatsinghpur', 'state' => 'Odisha'],
    'jajpur' => ['name' => 'Jajpur', 'state' => 'Odisha'],
    'jharsuguda' => ['name' => 'Jharsuguda', 'state' => 'Odisha'],
    'kalahandi' => ['name' => 'Kalahandi', 'state' => 'Odisha'],
    'kandhamal' => ['name' => 'Kandhamal', 'state' => 'Odisha'],
    'kendrapara' => ['name' => 'Kendrapara', 'state' => 'Odisha'],
    'kendujhar' => ['name' => 'Kendujhar', 'state' => 'Odisha'],
    'khordha' => ['name' => 'Khordha', 'state' => 'Odisha'],
    'koraput' => ['name' => 'Koraput', 'state' => 'Odisha'],
    'malkangiri' => ['name' => 'Malkangiri', 'state' => 'Odisha'],
    'mayurbhanj' => ['name' => 'Mayurbhanj', 'state' => 'Odisha'],
    'nabarangpur' => ['name' => 'Nabarangpur', 'state' => 'Odisha'],
    'nayagarh' => ['name' => 'Nayagarh', 'state' => 'Odisha'],
    'nuapada' => ['name' => 'Nuapada', 'state' => 'Odisha'],
    'puri' => ['name' => 'Puri', 'state' => 'Odisha'],
    'rayagada' => ['name' => 'Rayagada', 'state' => 'Odisha'],
    'sambalpur' => ['name' => 'Sambalpur', 'state' => 'Odisha'],
    'subarnapur' => ['name' => 'Subarnapur', 'state' => 'Odisha'],
    'sundergarh' => ['name' => 'Sundergarh', 'state' => 'Odisha'],
    'karaikal' => ['name' => 'Karaikal', 'state' => 'Puducherry'],
    'mahe' => ['name' => 'Mahe', 'state' => 'Puducherry'],
    'puducherry' => ['name' => 'Puducherry', 'state' => 'Puducherry'],
    'yanam' => ['name' => 'Yanam', 'state' => 'Puducherry'],
    'amritsar' => ['name' => 'Amritsar', 'state' => 'Punjab'],
    'barnala' => ['name' => 'Barnala', 'state' => 'Punjab'],
    'bathinda' => ['name' => 'Bathinda', 'state' => 'Punjab'],
    'faridkot' => ['name' => 'Faridkot', 'state' => 'Punjab'],
    'fatehgarh-sahib' => ['name' => 'Fatehgarh Sahib', 'state' => 'Punjab'],
    'fazilka' => ['name' => 'Fazilka', 'state' => 'Punjab'],
    'firozpur' => ['name' => 'Firozpur', 'state' => 'Punjab'],
    'gurdaspur' => ['name' => 'Gurdaspur', 'state' => 'Punjab'],
    'hoshiarpur' => ['name' => 'Hoshiarpur', 'state' => 'Punjab'],
    'jalandhar' => ['name' => 'Jalandhar', 'state' => 'Punjab'],
    'kapurthala' => ['name' => 'Kapurthala', 'state' => 'Punjab'],
    'ludhiana' => ['name' => 'Ludhiana', 'state' => 'Punjab'],
    'malerkotla' => ['name' => 'Malerkotla', 'state' => 'Punjab'],
    'mansa' => ['name' => 'Mansa', 'state' => 'Punjab'],
    'moga' => ['name' => 'Moga', 'state' => 'Punjab'],
    'mohali' => ['name' => 'Mohali', 'state' => 'Punjab'],
    'muktsar' => ['name' => 'Muktsar', 'state' => 'Punjab'],
    'pathankot' => ['name' => 'Pathankot', 'state' => 'Punjab'],
    'patiala' => ['name' => 'Patiala', 'state' => 'Punjab'],
    'rupnagar' => ['name' => 'Rupnagar', 'state' => 'Punjab'],
    'sangrur' => ['name' => 'Sangrur', 'state' => 'Punjab'],
    'shaheed-bhagat-singh-nagar' => ['name' => 'Shaheed Bhagat Singh Nagar', 'state' => 'Punjab'],
    'tarn-taran' => ['name' => 'Tarn Taran', 'state' => 'Punjab'],
    'ajmer' => ['name' => 'Ajmer', 'state' => 'Rajasthan'],
    'alwar' => ['name' => 'Alwar', 'state' => 'Rajasthan'],
    'anupgarh' => ['name' => 'Anupgarh', 'state' => 'Rajasthan'],
    'balotra' => ['name' => 'Balotra', 'state' => 'Rajasthan'],
    'banswara' => ['name' => 'Banswara', 'state' => 'Rajasthan'],
    'baran' => ['name' => 'Baran', 'state' => 'Rajasthan'],
    'barmer' => ['name' => 'Barmer', 'state' => 'Rajasthan'],
    'beawar' => ['name' => 'Beawar', 'state' => 'Rajasthan'],
    'bharatpur' => ['name' => 'Bharatpur', 'state' => 'Rajasthan'],
    'bhilwara' => ['name' => 'Bhilwara', 'state' => 'Rajasthan'],
    'bikaner' => ['name' => 'Bikaner', 'state' => 'Rajasthan'],
    'bundi' => ['name' => 'Bundi', 'state' => 'Rajasthan'],
    'chittorgarh' => ['name' => 'Chittorgarh', 'state' => 'Rajasthan'],
    'churu' => ['name' => 'Churu', 'state' => 'Rajasthan'],
    'dausa' => ['name' => 'Dausa', 'state' => 'Rajasthan'],
    'deeg' => ['name' => 'Deeg', 'state' => 'Rajasthan'],
    'dholpur' => ['name' => 'Dholpur', 'state' => 'Rajasthan'],
    'didwana-kuchaman' => ['name' => 'Didwana Kuchaman', 'state' => 'Rajasthan'],
    'dudu' => ['name' => 'Dudu', 'state' => 'Rajasthan'],
    'dungarpur' => ['name' => 'Dungarpur', 'state' => 'Rajasthan'],
    'gangapur-city' => ['name' => 'Gangapur City', 'state' => 'Rajasthan'],
    'hanumangarh' => ['name' => 'Hanumangarh', 'state' => 'Rajasthan'],
    'jaipur' => ['name' => 'Jaipur', 'state' => 'Rajasthan'],
    'jaipur-rural' => ['name' => 'Jaipur Rural', 'state' => 'Rajasthan'],
    'jaisalmer' => ['name' => 'Jaisalmer', 'state' => 'Rajasthan'],
    'jalore' => ['name' => 'Jalore', 'state' => 'Rajasthan'],
    'jhalawar' => ['name' => 'Jhalawar', 'state' => 'Rajasthan'],
    'jhunjhunu' => ['name' => 'Jhunjhunu', 'state' => 'Rajasthan'],
    'jodhpur' => ['name' => 'Jodhpur', 'state' => 'Rajasthan'],
    'jodhpur-rural' => ['name' => 'Jodhpur Rural', 'state' => 'Rajasthan'],
    'karauli' => ['name' => 'Karauli', 'state' => 'Rajasthan'],
    'kekri' => ['name' => 'Kekri', 'state' => 'Rajasthan'],
    'khairthal-tijara' => ['name' => 'Khairthal Tijara', 'state' => 'Rajasthan'],
    'kota' => ['name' => 'Kota', 'state' => 'Rajasthan'],
    'kotputli-behror' => ['name' => 'Kotputli Behror', 'state' => 'Rajasthan'],
    'nagaur' => ['name' => 'Nagaur', 'state' => 'Rajasthan'],
    'neem-ka-thana' => ['name' => 'Neem ka Thana', 'state' => 'Rajasthan'],
    'pali' => ['name' => 'Pali', 'state' => 'Rajasthan'],
    'phalodi' => ['name' => 'Phalodi', 'state' => 'Rajasthan'],
    'pratapgarh' => ['name' => 'Pratapgarh', 'state' => 'Rajasthan'],
    'rajsamand' => ['name' => 'Rajsamand', 'state' => 'Rajasthan'],
    'salumbar' => ['name' => 'Salumbar', 'state' => 'Rajasthan'],
    'sanchore' => ['name' => 'Sanchore', 'state' => 'Rajasthan'],
    'sawai-madhopur' => ['name' => 'Sawai Madhopur', 'state' => 'Rajasthan'],
    'shahpura' => ['name' => 'Shahpura', 'state' => 'Rajasthan'],
    'sikar' => ['name' => 'Sikar', 'state' => 'Rajasthan'],
    'sirohi' => ['name' => 'Sirohi', 'state' => 'Rajasthan'],
    'sri-ganganagar' => ['name' => 'Sri Ganganagar', 'state' => 'Rajasthan'],
    'tonk' => ['name' => 'Tonk', 'state' => 'Rajasthan'],
    'udaipur' => ['name' => 'Udaipur', 'state' => 'Rajasthan'],
    'east-sikkim' => ['name' => 'East Sikkim', 'state' => 'Sikkim'],
    'north-sikkim' => ['name' => 'North Sikkim', 'state' => 'Sikkim'],
    'pakyong' => ['name' => 'Pakyong', 'state' => 'Sikkim'],
    'soreng' => ['name' => 'Soreng', 'state' => 'Sikkim'],
    'south-sikkim' => ['name' => 'South Sikkim', 'state' => 'Sikkim'],
    'west-sikkim' => ['name' => 'West Sikkim', 'state' => 'Sikkim'],
    // Tamil Nadu cities already included above
    'adilabad' => ['name' => 'Adilabad', 'state' => 'Telangana'],
    'bhadradri-kothagudem' => ['name' => 'Bhadradri Kothagudem', 'state' => 'Telangana'],
    'hanamkonda' => ['name' => 'Hanamkonda', 'state' => 'Telangana'],
    'hyderabad' => ['name' => 'Hyderabad', 'state' => 'Telangana'],
    'jagtial' => ['name' => 'Jagtial', 'state' => 'Telangana'],
    'jangaon' => ['name' => 'Jangaon', 'state' => 'Telangana'],
    'jayashankar' => ['name' => 'Jayashankar', 'state' => 'Telangana'],
    'jogulamba' => ['name' => 'Jogulamba', 'state' => 'Telangana'],
    'kamareddy' => ['name' => 'Kamareddy', 'state' => 'Telangana'],
    'karimnagar' => ['name' => 'Karimnagar', 'state' => 'Telangana'],
    'khammam' => ['name' => 'Khammam', 'state' => 'Telangana'],
    'komaram-bheem' => ['name' => 'Komaram Bheem', 'state' => 'Telangana'],
    'mahabubabad' => ['name' => 'Mahabubabad', 'state' => 'Telangana'],
    'mahbubnagar' => ['name' => 'Mahbubnagar', 'state' => 'Telangana'],
    'mancherial' => ['name' => 'Mancherial', 'state' => 'Telangana'],
    'medak' => ['name' => 'Medak', 'state' => 'Telangana'],
    'medchal-malkajgiri' => ['name' => 'Medchal Malkajgiri', 'state' => 'Telangana'],
    'mulugu' => ['name' => 'Mulugu', 'state' => 'Telangana'],
    'nagarkurnool' => ['name' => 'Nagarkurnool', 'state' => 'Telangana'],
    'nalgonda' => ['name' => 'Nalgonda', 'state' => 'Telangana'],
    'narayanpet' => ['name' => 'Narayanpet', 'state' => 'Telangana'],
    'nirmal' => ['name' => 'Nirmal', 'state' => 'Telangana'],
    'nizamabad' => ['name' => 'Nizamabad', 'state' => 'Telangana'],
    'peddapalli' => ['name' => 'Peddapalli', 'state' => 'Telangana'],
    'rajanna-sircilla' => ['name' => 'Rajanna Sircilla', 'state' => 'Telangana'],
    'ranga-reddy' => ['name' => 'Ranga Reddy', 'state' => 'Telangana'],
    'sangareddy' => ['name' => 'Sangareddy', 'state' => 'Telangana'],
    'siddipet' => ['name' => 'Siddipet', 'state' => 'Telangana'],
    'suryapet' => ['name' => 'Suryapet', 'state' => 'Telangana'],
    'vikarabad' => ['name' => 'Vikarabad', 'state' => 'Telangana'],
    'wanaparthy' => ['name' => 'Wanaparthy', 'state' => 'Telangana'],
    'warangal' => ['name' => 'Warangal', 'state' => 'Telangana'],
    'yadadri-bhuvanagiri' => ['name' => 'Yadadri Bhuvanagiri', 'state' => 'Telangana'],
    'dhalai' => ['name' => 'Dhalai', 'state' => 'Tripura'],
    'gomati' => ['name' => 'Gomati', 'state' => 'Tripura'],
    'khowai' => ['name' => 'Khowai', 'state' => 'Tripura'],
    'north-tripura' => ['name' => 'North Tripura', 'state' => 'Tripura'],
    'sepahijala' => ['name' => 'Sepahijala', 'state' => 'Tripura'],
    'south-tripura' => ['name' => 'South Tripura', 'state' => 'Tripura'],
    'unakoti' => ['name' => 'Unakoti', 'state' => 'Tripura'],
    'west-tripura' => ['name' => 'West Tripura', 'state' => 'Tripura'],
    'agra' => ['name' => 'Agra', 'state' => 'Uttar Pradesh'],
    'aligarh' => ['name' => 'Aligarh', 'state' => 'Uttar Pradesh'],
    'ambedkar-nagar' => ['name' => 'Ambedkar Nagar', 'state' => 'Uttar Pradesh'],
    'amethi' => ['name' => 'Amethi', 'state' => 'Uttar Pradesh'],
    'amroha' => ['name' => 'Amroha', 'state' => 'Uttar Pradesh'],
    'auraiya' => ['name' => 'Auraiya', 'state' => 'Uttar Pradesh'],
    'ayodhya' => ['name' => 'Ayodhya', 'state' => 'Uttar Pradesh'],
    'azamgarh' => ['name' => 'Azamgarh', 'state' => 'Uttar Pradesh'],
    'baghpat' => ['name' => 'Baghpat', 'state' => 'Uttar Pradesh'],
    'bahraich' => ['name' => 'Bahraich', 'state' => 'Uttar Pradesh'],
    'ballia' => ['name' => 'Ballia', 'state' => 'Uttar Pradesh'],
    'banda' => ['name' => 'Banda', 'state' => 'Uttar Pradesh'],
    'barabanki' => ['name' => 'Barabanki', 'state' => 'Uttar Pradesh'],
    'bareilly' => ['name' => 'Bareilly', 'state' => 'Uttar Pradesh'],
    'basti' => ['name' => 'Basti', 'state' => 'Uttar Pradesh'],
    'bhadohi' => ['name' => 'Bhadohi', 'state' => 'Uttar Pradesh'],
    'bijnor' => ['name' => 'Bijnor', 'state' => 'Uttar Pradesh'],
    'budaun' => ['name' => 'Budaun', 'state' => 'Uttar Pradesh'],
    'bulandshahr' => ['name' => 'Bulandshahr', 'state' => 'Uttar Pradesh'],
    'chandauli' => ['name' => 'Chandauli', 'state' => 'Uttar Pradesh'],
    'chitrakoot' => ['name' => 'Chitrakoot', 'state' => 'Uttar Pradesh'],
    'deoria' => ['name' => 'Deoria', 'state' => 'Uttar Pradesh'],
    'etah' => ['name' => 'Etah', 'state' => 'Uttar Pradesh'],
    'etawah' => ['name' => 'Etawah', 'state' => 'Uttar Pradesh'],
    'farrukhabad' => ['name' => 'Farrukhabad', 'state' => 'Uttar Pradesh'],
    'fatehpur' => ['name' => 'Fatehpur', 'state' => 'Uttar Pradesh'],
    'firozabad' => ['name' => 'Firozabad', 'state' => 'Uttar Pradesh'],
    'gautam-buddha-nagar' => ['name' => 'Gautam Buddha Nagar', 'state' => 'Uttar Pradesh'],
    'ghaziabad' => ['name' => 'Ghaziabad', 'state' => 'Uttar Pradesh'],
    'ghazipur' => ['name' => 'Ghazipur', 'state' => 'Uttar Pradesh'],
    'gonda' => ['name' => 'Gonda', 'state' => 'Uttar Pradesh'],
    'gorakhpur' => ['name' => 'Gorakhpur', 'state' => 'Uttar Pradesh'],
    'hapur' => ['name' => 'Hapur', 'state' => 'Uttar Pradesh'],
    'hardoi' => ['name' => 'Hardoi', 'state' => 'Uttar Pradesh'],
    'hathras' => ['name' => 'Hathras', 'state' => 'Uttar Pradesh'],
    'jalaun' => ['name' => 'Jalaun', 'state' => 'Uttar Pradesh'],
    'jaunpur' => ['name' => 'Jaunpur', 'state' => 'Uttar Pradesh'],
    'jhansi' => ['name' => 'Jhansi', 'state' => 'Uttar Pradesh'],
    'kannauj' => ['name' => 'Kannauj', 'state' => 'Uttar Pradesh'],
    'kanpur-dehat' => ['name' => 'Kanpur Dehat', 'state' => 'Uttar Pradesh'],
    'kanpur-nagar' => ['name' => 'Kanpur Nagar', 'state' => 'Uttar Pradesh'],
    'kasganj' => ['name' => 'Kasganj', 'state' => 'Uttar Pradesh'],
    'kaushambi' => ['name' => 'Kaushambi', 'state' => 'Uttar Pradesh'],
    'kushinagar' => ['name' => 'Kushinagar', 'state' => 'Uttar Pradesh'],
    'lakhimpur-kheri' => ['name' => 'Lakhimpur Kheri', 'state' => 'Uttar Pradesh'],
    'lalitpur' => ['name' => 'Lalitpur', 'state' => 'Uttar Pradesh'],
    'lucknow' => ['name' => 'Lucknow', 'state' => 'Uttar Pradesh'],
    'maharajganj' => ['name' => 'Maharajganj', 'state' => 'Uttar Pradesh'],
    'mahoba' => ['name' => 'Mahoba', 'state' => 'Uttar Pradesh'],
    'mainpuri' => ['name' => 'Mainpuri', 'state' => 'Uttar Pradesh'],
    'mathura' => ['name' => 'Mathura', 'state' => 'Uttar Pradesh'],
    'mau' => ['name' => 'Mau', 'state' => 'Uttar Pradesh'],
    'meerut' => ['name' => 'Meerut', 'state' => 'Uttar Pradesh'],
    'mirzapur' => ['name' => 'Mirzapur', 'state' => 'Uttar Pradesh'],
    'moradabad' => ['name' => 'Moradabad', 'state' => 'Uttar Pradesh'],
    'muzaffarnagar' => ['name' => 'Muzaffarnagar', 'state' => 'Uttar Pradesh'],
    'pilibhit' => ['name' => 'Pilibhit', 'state' => 'Uttar Pradesh'],
    'prayagraj' => ['name' => 'Prayagraj', 'state' => 'Uttar Pradesh'],
    'raebareli' => ['name' => 'Raebareli', 'state' => 'Uttar Pradesh'],
    'rampur' => ['name' => 'Rampur', 'state' => 'Uttar Pradesh'],
    'saharanpur' => ['name' => 'Saharanpur', 'state' => 'Uttar Pradesh'],
    'sambhal' => ['name' => 'Sambhal', 'state' => 'Uttar Pradesh'],
    'sant-kabir-nagar' => ['name' => 'Sant Kabir Nagar', 'state' => 'Uttar Pradesh'],
    'shahjahanpur' => ['name' => 'Shahjahanpur', 'state' => 'Uttar Pradesh'],
    'shamli' => ['name' => 'Shamli', 'state' => 'Uttar Pradesh'],
    'shravasti' => ['name' => 'Shravasti', 'state' => 'Uttar Pradesh'],
    'siddharthnagar' => ['name' => 'Siddharthnagar', 'state' => 'Uttar Pradesh'],
    'sitapur' => ['name' => 'Sitapur', 'state' => 'Uttar Pradesh'],
    'sonbhadra' => ['name' => 'Sonbhadra', 'state' => 'Uttar Pradesh'],
    'sultanpur' => ['name' => 'Sultanpur', 'state' => 'Uttar Pradesh'],
    'unnao' => ['name' => 'Unnao', 'state' => 'Uttar Pradesh'],
    'varanasi' => ['name' => 'Varanasi', 'state' => 'Uttar Pradesh'],
    'almora' => ['name' => 'Almora', 'state' => 'Uttarakhand'],
    'bageshwar' => ['name' => 'Bageshwar', 'state' => 'Uttarakhand'],
    'chamoli' => ['name' => 'Chamoli', 'state' => 'Uttarakhand'],
    'champawat' => ['name' => 'Champawat', 'state' => 'Uttarakhand'],
    'dehradun' => ['name' => 'Dehradun', 'state' => 'Uttarakhand'],
    'haridwar' => ['name' => 'Haridwar', 'state' => 'Uttarakhand'],
    'nainital' => ['name' => 'Nainital', 'state' => 'Uttarakhand'],
    'pauri' => ['name' => 'Pauri', 'state' => 'Uttarakhand'],
    'pithoragarh' => ['name' => 'Pithoragarh', 'state' => 'Uttarakhand'],
    'rudraprayag' => ['name' => 'Rudraprayag', 'state' => 'Uttarakhand'],
    'tehri' => ['name' => 'Tehri', 'state' => 'Uttarakhand'],
    'udham-singh-nagar' => ['name' => 'Udham Singh Nagar', 'state' => 'Uttarakhand'],
    'uttarkashi' => ['name' => 'Uttarkashi', 'state' => 'Uttarakhand'],
    'alipurduar' => ['name' => 'Alipurduar', 'state' => 'West Bengal'],
    'bankura' => ['name' => 'Bankura', 'state' => 'West Bengal'],
    'birbhum' => ['name' => 'Birbhum', 'state' => 'West Bengal'],
    'cooch-behar' => ['name' => 'Cooch Behar', 'state' => 'West Bengal'],
    'dakshin-dinajpur' => ['name' => 'Dakshin Dinajpur', 'state' => 'West Bengal'],
    'darjeeling' => ['name' => 'Darjeeling', 'state' => 'West Bengal'],
    'hooghly' => ['name' => 'Hooghly', 'state' => 'West Bengal'],
    'howrah' => ['name' => 'Howrah', 'state' => 'West Bengal'],
    'jalpaiguri' => ['name' => 'Jalpaiguri', 'state' => 'West Bengal'],
    'jhargram' => ['name' => 'Jhargram', 'state' => 'West Bengal'],
    'kalimpong' => ['name' => 'Kalimpong', 'state' => 'West Bengal'],
    'kolkata' => ['name' => 'Kolkata', 'state' => 'West Bengal'],
    'malda' => ['name' => 'Malda', 'state' => 'West Bengal'],
    'murshidabad' => ['name' => 'Murshidabad', 'state' => 'West Bengal'],
    'nadia' => ['name' => 'Nadia', 'state' => 'West Bengal'],
    'north-24-parganas' => ['name' => 'North 24 Parganas', 'state' => 'West Bengal'],
    'paschim-bardhaman' => ['name' => 'Paschim Bardhaman', 'state' => 'West Bengal'],
    'paschim-medinipur' => ['name' => 'Paschim Medinipur', 'state' => 'West Bengal'],
    'purba-bardhaman' => ['name' => 'Purba Bardhaman', 'state' => 'West Bengal'],
    'purba-medinipur' => ['name' => 'Purba Medinipur', 'state' => 'West Bengal'],
    'purulia' => ['name' => 'Purulia', 'state' => 'West Bengal'],
    'south-24-parganas' => ['name' => 'South 24 Parganas', 'state' => 'West Bengal'],
    'uttar-dinajpur' => ['name' => 'Uttar Dinajpur', 'state' => 'West Bengal'],
    'andaman-nicobar' => ['name' => 'Andaman Nicobar', 'state' => 'Andaman and Nicobar Islands'],
    'andhra-pradesh' => ['name' => 'Andhra Pradesh', 'state' => 'Andhra Pradesh'],
    'arunachal-pradesh' => ['name' => 'Arunachal Pradesh', 'state' => 'Arunachal Pradesh'],
    'assam' => ['name' => 'Assam', 'state' => 'Assam'],
    'bihar' => ['name' => 'Bihar', 'state' => 'Bihar'],
    'chhattisgarh' => ['name' => 'Chhattisgarh', 'state' => 'Chhattisgarh'],
    'dadra-nagar-haveli-and-daman-and-diu' => ['name' => 'Dadra Nagar Haveli and Daman and Diu', 'state' => 'Dadra and Nagar Haveli and Daman and Diu'],
    'delhi' => ['name' => 'Delhi', 'state' => 'Delhi'],
    'goa' => ['name' => 'Goa', 'state' => 'Goa'],
    'gujarat' => ['name' => 'Gujarat', 'state' => 'Gujarat'],
    'haryana' => ['name' => 'Haryana', 'state' => 'Haryana'],
    'himachal-pradesh' => ['name' => 'Himachal Pradesh', 'state' => 'Himachal Pradesh'],
    'jammu-kashmir' => ['name' => 'Jammu Kashmir', 'state' => 'Jammu and Kashmir'],
    'jharkhand' => ['name' => 'Jharkhand', 'state' => 'Jharkhand'],
    'karnataka' => ['name' => 'Karnataka', 'state' => 'Karnataka'],
    'kerala' => ['name' => 'Kerala', 'state' => 'Kerala'],
    'ladakh' => ['name' => 'Ladakh', 'state' => 'Ladakh'],
    'madhya-pradesh' => ['name' => 'Madhya Pradesh', 'state' => 'Madhya Pradesh'],
    'maharashtra' => ['name' => 'Maharashtra', 'state' => 'Maharashtra'],
    'manipur' => ['name' => 'Manipur', 'state' => 'Manipur'],
    'meghalaya' => ['name' => 'Meghalaya', 'state' => 'Meghalaya'],
    'mizoram' => ['name' => 'Mizoram', 'state' => 'Mizoram'],
    'nagaland' => ['name' => 'Nagaland', 'state' => 'Nagaland'],
    'odisha' => ['name' => 'Odisha', 'state' => 'Odisha'],
    'punjab' => ['name' => 'Punjab', 'state' => 'Punjab'],
    'rajasthan' => ['name' => 'Rajasthan', 'state' => 'Rajasthan'],
    'sikkim' => ['name' => 'Sikkim', 'state' => 'Sikkim'],
    // Tamil Nadu already included
    'telangana' => ['name' => 'Telangana', 'state' => 'Telangana'],
    'tripura' => ['name' => 'Tripura', 'state' => 'Tripura'],
    'uttar-pradesh' => ['name' => 'Uttar Pradesh', 'state' => 'Uttar Pradesh'],
    'uttarakhand' => ['name' => 'Uttarakhand', 'state' => 'Uttarakhand'],
    'west-bengal' => ['name' => 'West Bengal', 'state' => 'West Bengal']
];

// Merge the new cities/districts/states into the existing supportedCities array
$supportedCities = array_merge($supportedCities, $newCities);

// Redirect to main SEO page if city not found
if (!array_key_exists($citySlug, $supportedCities)) {
    header("Location: /seo-services.php");
    exit();
}
// Get city data
$cityData = $supportedCities[$citySlug];
$fullCityName = $cityData['name'];
$stateName = $cityData['state'];
// Dynamic SEO variables for this city page
$page_title = "Best SEO Services in {$fullCityName} | ThiyagiDigital";
$page_description = "Professional SEO services in {$fullCityName}, {$stateName}. Boost your local search rankings with our expert SEO strategies.";
$page_keywords = "SEO services {$fullCityName}, digital marketing {$fullCityName}, local SEO {$fullCityName}";
$canonical_url = "https://www.thiyagidigital.com/seo-services/{$citySlug}";
// $og_image = '/assets/img/service/serd1.jpg';
// Add BreadcrumbList + FAQPage JSON-LD via @graph
$serviceName = 'SEO Services';
$serviceUrl = 'https://www.thiyagidigital.com/seo-services.php';
$breadcrumbSchema = [
    '@type' => 'BreadcrumbList',
    'itemListElement' => [
        [
            '@type' => 'ListItem',
            'position' => 1,
            'name' => 'Home',
            'item' => 'https://www.thiyagidigital.com/'
        ],
        [
            '@type' => 'ListItem',
            'position' => 2,
            'name' => $serviceName,
            'item' => $serviceUrl
        ],
        [
            '@type' => 'ListItem',
            'position' => 3,
            'name' => $serviceName . ' in ' . $fullCityName,
            'item' => $canonical_url
        ]
    ]
];
$faqSchema = [
    '@type' => 'FAQPage',
    'mainEntity' => [
        [
            '@type' => 'Question',
            'name' => 'What is SEO?',
            'acceptedAnswer' => [
                '@type' => 'Answer',
                'text' => "SEO, or Search Engine Optimization, improves website visibility and rankings on search engines for queries like 'SEO services in {$fullCityName}'."
            ]
        ],
        [
            '@type' => 'Question',
            'name' => "Why is local SEO important for {$fullCityName} businesses?",
            'acceptedAnswer' => [
                '@type' => 'Answer',
                'text' => "Local SEO increases your visibility in {$fullCityName}, attracting targeted local traffic and boosting leads and revenue."
            ]
        ],
        [
            '@type' => 'Question',
            'name' => "How long does it take to see SEO results in {$fullCityName}?",
            'acceptedAnswer' => [
                '@type' => 'Answer',
                'text' => 'Timelines vary, but many businesses notice improvements within 4â€“6 months, with ongoing optimization for sustained growth.'
            ]
        ]
    ]
];
$page_schema = [
    '@context' => 'https://schema.org',
    '@graph' => [ $breadcrumbSchema, $faqSchema ]
];
?>
<?php include 'header.php';?>
<!-- Start of breadcrumb section -->
<section id="bi-breadcrumbs" class="bi-bredcrumbs-section position-relative about-bgimgsize" data-background="/assets/img/bg/bread-bg.jpg">
    <div class="background_overlay"></div>
    <div class="container">
        <div class="bi-breadcrumbs-content headline ul-li text-center">
            <h1 style="color: white"><b>Best SEO Services in <?php echo $fullCityName; ?> - ThiyagiDigital</b></h1><br>
            <ul>
                <li><a href="/">Home</a></li>
                <li><a href="#">Services</a></li>
                <li style="color: white">SEO in <?php echo $fullCityName; ?></li>
            </ul>
        </div>
    </div>
</section>
<!-- End of breadcrumb section -->
<!-- Start of Service Details section -->
<section id="bi-service-details" class="bi-service-details-section inner-page-padding">
    <div class="container">
        <div class="bi-service-details-content">
            <div class="row">
                <div class="col-lg-8">
                    <div class="bi-service-details-text-area">
                        <div class="bi-service-details-img">
                            <img src="/assets/img/service/serd1.jpg" alt="SEO Services in <?php echo $fullCityName; ?>">
                        </div>
                        <div class="bi-service-details-text headline pera-content">
                            <h3>Search Engine Optimization in <?php echo $fullCityName; ?></h3>
                            <p>In the digital landscape of <?php echo $fullCityName; ?>, visibility is key, and that's where our Search Engine Optimization (SEO) services come into play. At ThiyagiDigital, we specialize in propelling your <?php echo $fullCityName; ?> business to the top of search engine results, ensuring your brand stands out in the competitive online arena.</p>
                            <p>Our seasoned SEO experts in <?php echo $fullCityName; ?> employ a strategic approach, conducting in-depth keyword research specific to your area, optimizing on-page elements, and building high-quality backlinks to enhance your website's authority for local searches.</p>
                            <p>We don't believe in one-size-fits-all solutions. Each <?php echo $fullCityName; ?> client receives a tailored SEO strategy crafted to address specific business goals and local market nuances. Whether you're aiming to boost visibility in <?php echo $fullCityName; ?> or reach a regional audience, we have the expertise to make it happen.</p>
                            <h4>"Elevate Your <?php echo $fullCityName; ?> Online Presence with Our SEO Services"</h4>
                            <p>We place a higher priority on producing observable results than rankings. Our all-inclusive SEO services for <?php echo $fullCityName; ?> businesses are made to improve user experience as well as organic traffic, which will raise conversions and support long-term business success in <?php echo $stateName; ?>.</p>
                            <p>Partner with us, and let's unlock the full potential of your online presence in <?php echo $fullCityName; ?>. Dominate search engine results, attract your target audience, and watch your business thrive in the digital realm. Invest in SEO with Thiyagidigitalâ€”where visibility transforms into profitability.</p>
                            <h4>Frequently Asked Questions About SEO in <?php echo $fullCityName; ?></h4>
                            <div class="bi-faq-content-area">
                                <div class="accordion" id="accordionExample_31">
                                    <div class="accordion-item wow fadeInUp" data-wow-delay="200ms" data-wow-duration="1000ms">
                                        <h2 class="accordion-header" id="heading10">
                                            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse10" aria-expanded="true" aria-controls="collapse10">
                                                <span>What is SEO?</span>
                                            </button>
                                        </h2>
                                        <div id="collapse10" class="accordion-collapse collapse show" aria-labelledby="heading10" data-bs-parent="#accordionExample_31">
                                            <div class="accordion-body">
                                                <div class="bi-faq-text">
                                                SEO, or Search Engine Optimization, is the process of optimizing websites to improve visibility and rankings on search engines for terms like "SEO services in <?php echo $fullCityName; ?>".
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="accordion-item wow fadeInUp" data-wow-delay="300ms" data-wow-duration="1000ms">
                                        <h2 class="accordion-header" id="heading12">
                                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse12" aria-expanded="false" aria-controls="collapse12">
                                                <span>Why is local SEO important for <?php echo $fullCityName; ?> businesses?</span>
                                            </button>
                                        </h2>
                                        <div id="collapse12" class="accordion-collapse collapse" aria-labelledby="heading12" data-bs-parent="#accordionExample_31">
                                            <div class="accordion-body">
                                                <div class="bi-faq-text">
                                                Local SEO enhances your visibility in <?php echo $fullCityName; ?>, attracts targeted local traffic, and boosts credibility among <?php echo $fullCityName; ?> customers, ultimately contributing to increased leads and revenue.
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="accordion-item wow fadeInUp" data-wow-delay="400ms" data-wow-duration="1000ms">
                                        <h2 class="accordion-header" id="heading13">
                                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse13" aria-expanded="false" aria-controls="collapse13">
                                                <span>How long does it take to see SEO results in <?php echo $fullCityName; ?>?</span>
                                            </button>
                                        </h2>
                                        <div id="collapse13" class="accordion-collapse collapse" aria-labelledby="heading13" data-bs-parent="#accordionExample_31">
                                            <div class="accordion-body">
                                                <div class="bi-faq-text">
                                                SEO timelines vary for <?php echo $fullCityName; ?> businesses, but noticeable improvements often occur in 4-6 months; sustained success involves ongoing optimization efforts tailored to the <?php echo $fullCityName; ?> market.
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="bi-single-sidebar">
                        <div class="container">
                            <?php include 'sideform.php';?>
                            <?php include 'mainservice-sidebar.php';?>
                            <div class="bi-single-sidebar-item">
                                <div class="bi-sidebar-contact-widget headline">
                                    <h3 class="widget-title">Serving <?php echo $fullCityName; ?> Area</h3>
                                    <p>We provide specialized SEO services for businesses in <?php echo $fullCityName; ?>, <?php echo $stateName; ?>.</p>
                                </div>
                            </div>
                            <div class="bi-single-sidebar-item">
                                <div class="bi-sidebar-contact-widget headline">
                                    <h3 class="widget-title">Quick FAQs: SEO in <?php echo $fullCityName; ?></h3>
                                    <div class="bi-faq-content-area">
                                        <div class="accordion" id="accordionSidebarSEO">
                                            <div class="accordion-item">
                                                <h2 class="accordion-header" id="sfaq1">
                                                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sfaq1c" aria-expanded="false" aria-controls="sfaq1c">
                                                        What is SEO?
                                                    </button>
                                                </h2>
                                                <div id="sfaq1c" class="accordion-collapse collapse" aria-labelledby="sfaq1" data-bs-parent="#accordionSidebarSEO">
                                                    <div class="accordion-body">
                                                        SEO improves your websiteâ€™s visibility on search engines for local terms like â€œSEO services in <?php echo $fullCityName; ?>â€.
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="accordion-item">
                                                <h2 class="accordion-header" id="sfaq2">
                                                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sfaq2c" aria-expanded="false" aria-controls="sfaq2c">
                                                        Why is local SEO important?
                                                    </button>
                                                </h2>
                                                <div id="sfaq2c" class="accordion-collapse collapse" aria-labelledby="sfaq2" data-bs-parent="#accordionSidebarSEO">
                                                    <div class="accordion-body">
                                                        It helps businesses in <?php echo $fullCityName; ?> reach nearby customers, boosting relevant traffic and leads.
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="accordion-item">
                                                <h2 class="accordion-header" id="sfaq3">
                                                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sfaq3c" aria-expanded="false" aria-controls="sfaq3c">
                                                        How long to see results?
                                                    </button>
                                                </h2>
                                                <div id="sfaq3c" class="accordion-collapse collapse" aria-labelledby="sfaq3" data-bs-parent="#accordionSidebarSEO">
                                                    <div class="accordion-body">
                                                        Typically 4â€“6 months, depending on competition in <?php echo $fullCityName; ?> and your siteâ€™s starting point.
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <?php include 'callservice-sidebar.php';?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- End of Service Details section -->
    <?php include 'testmonial2.php';?>
    <?php include 'client-logo.php';?>
    <?php include 'project-count.php';?>
    <?php include 'certify-partner.php';?>
    <?php include 'footer.php';?>